### ISSUE TITLE
Get image from items inside folder

### ISSUE THREAD

**Issue by kerngebiet-digital** [typemill/typemill#102]
Hello,

i want to list items from an folder including the first image of each entry. Is this possible, an upcoming feature or extendable by a plugin?

Regards
Chris

**Comment by trendschau** [comment]
Hi Chris,

unfortunately this is not easily possible right now, but it is an important feature, so I will add it to release 1.3.5. Release 1.3.4 with a new media-library will be published tomorrow probably.

Just as a implementation-reminder for me:

* Add field for hero-image to meta-tag
* For each image that is published on a page, check if hero-image is set already
* if not, set it.

That's it basically, but requires an image field-type for the form-builder...

**Comment by trendschau** [comment]
If this is very urgent, then there might be another (more dirty) workaround:

* I have to add an event onPublishArticle (which is planned anyway)
* Create a plugin that listens to the event.
* When page is published, parse it, search for image and write it to the yaml-file of that page.

I could add that event to the release tomorrow and you could create your own plugin then.

**Comment by kerngebiet-digital** [comment]
Thank you for the great response! Its not urgent but important for daily use. I try to add a custom field in meta where i put the preview image url. Very curious about the next release!

Regards
Chris

**Comment by trendschau** [comment]
Yes, that is a simple and clever workaround! :)

**Comment by kerngebiet-digital** [comment]
Ok but i dont get the metatabs content outside of the detail page?

**Comment by trendschau** [comment]
Yes, you can, it is described here: https://typemill.net/theme-developers/helper-functions#list-articles

I am not super sure, what you want to achive. Generally, you can use the meta-content of pages inside a folder wherever you want. An example of this can be found in the dev-theme or in the emergency theme: https://themes.typemill.net/

This only works with pages inside a folder. If you want to get the meta-information of one special page: That is not possible right now but I can implement that in the next release, such a feature makes sense...

I will implement an image-fied-type for the next release, too (or try to) ...

**Comment by trendschau** [comment]
or better said: the function `getPageMeta(settings, article)` is there already, but you need to get the item-object (= article) of the page. I am in a hurry right now and have to look into the code if there is some workaround already ...

**Comment by kerngebiet-digital** [comment]
Very nice `getPageMeta(settings, article)` helped. Its not that intuitive at first but performance driven.

**Comment by trendschau** [comment]
Preview of the next version 1.3.6, it provides a new field-type for images that you can use in meta-tabs:

![heroimage](https://user-images.githubusercontent.com/2714547/80679658-9dda4180-8abd-11ea-8776-bef57ca2e449.gif)

**Comment by trendschau** [comment]
published with version 1.3.6 today
