### ISSUE TITLE
Cannot install new themes

### ISSUE THREAD

**Issue by timwasson** [typemill/typemill#103]
I have tried installing the dev theme locally, as well as a custom-made theme using the instructions in the docs, but every time I get this error when trying to set the new theme:

```There is no theme in the theme-folder. Please add a theme from https://themes.typemill.net```

If I remove the new theme, the error persists. The only way I can solve the issue is to remove the entire typemill directory and starting from scratch. 

I have not tried this on a Linux server. This is all tested through my Mac. 

PHP version PHP 7.3.11.

**Comment by timwasson** [comment]
I resolved this my commenting out line 37 in Settings.php, which allowed me to view and set the theme. Then I un-commented it and now it seems to work fine. This doesn't seem like a normal part of the workflow though.

**Comment by trendschau** [comment]
Hi Tim, thank you for reporting it, I will have a look into it and optimize the theme handling in the next release...

**Comment by trendschau** [comment]
improvement published with version 1.3.5

The minimum requirement of a new theme is an `index.twig`-file, so the system looks for it. If there is a theme-folder without that file (and other valid theme), then the system will die with an error.
