### ISSUE TITLE
Minor problems v 1.3.4

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#110]
1. If Typemill standard theme is set to »Active special Startpage-Design«, the browser tab shows the url, should show the website's title once. Functioned in previous versions. 
2. In browser mode, if a page is set to »hidden from navigation« and shown (via link reference), pressing F5 »refresh page«, one gets the error »Not Found«. 
3. In browser mode, if a page is set to »hidden from navigation«, it is still shown within the posts list and can be accessed. 
4. Inserting a page/folder and setting a capitalized content title, changing an item on that meta page results in a lower case navigation title. It can be overcome by changing the meta navigation title, but this is another working step and irritating. 
5. If a folder's sorting is set to »posts«, added pages show in the life navigation. To avoid clutter, those pages must be explicitly set to »hide«. Suggestion: All pages of such a folder should automatically be set to hidden (ideally steered by an optional choice).  
6. For some unknown irreproducible reason changing an item on the meta page, the »last modified live« is deleted, resulting in error »modified is not a valid date«, so that changes can not be saved. Setting the »manual date« does not change the »last modified«.

**Comment by trendschau** [comment]
Thank you for reporting, I will fix all bugs with the next release "consolidation" ...

**Comment by trendschau** [comment]
fixed all reported problems for version 1.3.5.

**Comment by trendschau** [comment]
published with version 1.3.5
