### ISSUE TITLE
Caption not showing at the appropriate place and width (v 1.3.4)

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#114]
The caption has to be shown below the picture, which is standard procedure in publishing. 
Also, the caption has to be set relative in size to the chosen picture. The caption line must be in line with the width of the picture and, if necessary, should be wrapped accordingly.

**Comment by trendschau** [comment]
Yes, that is true. Markdown does not support captions at all, the implementation of Typemill is just a hack with limitations. 

The question is how to deal with it. The overall goal of Typemill is to convert the website into a book in near or far future. This will probably be done by some kind of service using pandoc. It does not make sense to implement a special "caption"-feature for Typemil that is not recognized by pandoc later. Pandoc has an extension for image captions: https://pandoc.org/MANUAL.html#images , but they use the alt-text as caption text. On a website, the alt text should describe the subject/motif of an image for screen readers, while a caption should provide additional information, so this is not a clean solution at all (and it would be some kind of breaking change). 

Hard to decide what to do here, so it needs some further research and thinking to find a proper solution ...

**Comment by DialogusOne** [comment]
Yes, it won’t be easy to solve. I doubt that Pandoc’s way of using the image’s alt-text is a long-term good solution. Perhaps you think again about including some html-functions in Typemill. 

Here are two articles going into more depth with caption and showing a possible way out:
https://helpx.adobe.com/de/indesign/using/captions.html
https://maurice-web.de/bildunterschrift-an-bild-anpassen-mit-min-content-inklusive-ie/

Best

**Comment by trendschau** [comment]
Will try to improve with the proposal of Tekl in issue #130

**Comment by trendschau** [comment]
Finally decided for html5 figure tag. This does only apply to images in a separate tag and does not apply to linked images right now.

Here is an example: https://typemill.net/info/markdown-test#images
