### ISSUE TITLE
Sorry: Rusty html: url forward to Blog

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#120]
I'm used to forward url's internally in ordinary old time html pages, but have to ask here: is there a simple way to forward direktly to the Blog in for instance the 'About Me' theme?

(Love the Blog possibility <3 - thx!)

**Comment by trendschau** [comment]
Hi Carsten, 

glad to hear that you like the blog possibilities! 

You want to show the list of posts on the startpage, correct? 

That is generally possible, you can generally show the content of folders everywhere. But it requires a little bit of code in the theme, described here:  https://typemill.net/theme-developers/helper-functions#list-articles

Maybe I can add that possibility in the next release of the theme, but it is quite a lot of work to update all themes with all functionalities of typemill...
