### ISSUE TITLE
1.0.0 — Plugin Search

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#122]
1. After inserting a search phrase, the start should be activated by hitting the keyboard return/enter and not explicitly clicking on the go-button. 
2. The results page shows the raw view, which is not a user friendly view.
3. The results page shows the first lines of an entry; rather, it should show an entry title plus the context-dependant search phrase. When opening an entry the search phrase should be highlighted within the text. At present, one has to search manually to the spot.

**Comment by trendschau** [comment]
The search plugin is a sponsored feature by vodaris. The improvements that you mention are planned for a version 1.1.0, but I won't find the time to implement in near future due to a fully stuffed roadmap.

Related issues #49 and #71

**Comment by trendschau** [comment]
Will check it again for new search plugin (with license).
