### ISSUE TITLE
Allow other url-schemes

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#123]
Hi,

I want to use some URLs like this: `dict://Workload`. This url scheme is registered for the Dictionary Application from macOS. Is there a way to configure the allowed schemes?

**Comment by trendschau** [comment]
unfortunately that is not possible and i won't implement something like that for Typemill. 

But you can have a look into issue #72 As a quick idea: You can try to create a plugin, extend the slim-class URI and then manipulate the scheme. https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php

 Not sure if that works but maybe worth a try...

**Comment by Tekl** [comment]
Thanks for you answer. Creating a plugin is out of my reach at the moment. :-( I also tried to enter plain HTML but that seems not to be allowed in Typemill, right?

**Comment by trendschau** [comment]
Sorry, reading this again I misunderstood your issue: You want to enter an outside link to dict://... correct? That is not too hard, you have to extend the whitelist for links of the markdown parser (parsedown). https://github.com/parsedown/parsedown/blob/master/Parsedown.php

I can extend it for release 1.4.1 if it is still needed.

**Comment by Tekl** [comment]
A prebuild addition to the whitelist would be nice. If I do it myself is there a way to alter the whitelist without modifing the Parsedown.php? Otherwise I've to remember to alter the files with every update.

**Comment by trendschau** [comment]
I think it is possible as an additional developer setting, I will try.

**Comment by trendschau** [comment]
I had to postpone it, will try to implement with version 1.4.2

**Comment by trendschau** [comment]
published with version 1.4.2
