### ISSUE TITLE
🛠Missing/not working translation strings + css problems

### ISSUE THREAD

**Issue by hide-me** [typemill/typemill#124]
Below in the screenshots, I noted phrases that cannot be translated, because they are not in the file for translation, or are present in the file for translation but do not work.
Arrows indicate places that look extremely messy due to the fact that words in different languages ​​have different lengths.

Separately, I would like to ask you to implement the installation process also in different languages, so that language support is at all stages.

I also want to ask to realize the ability to translate plugins and themes. To make the CMS look as user-friendly as possible.

![m0](https://user-images.githubusercontent.com/45032974/80317424-6002c200-880c-11ea-8be2-d913df1b6bfe.png)
![m1](https://user-images.githubusercontent.com/45032974/80317426-6133ef00-880c-11ea-8842-62e2d01c5d87.png)
![m2](https://user-images.githubusercontent.com/45032974/80317429-61cc8580-880c-11ea-9380-b2743e3a7d5a.png)
![m3](https://user-images.githubusercontent.com/45032974/80317431-63964900-880c-11ea-9af2-ff6756e293cc.png)
![m4](https://user-images.githubusercontent.com/45032974/80317435-65600c80-880c-11ea-9cfb-ed88008f157a.png)
![m5](https://user-images.githubusercontent.com/45032974/80317436-66913980-880c-11ea-9bda-0650525ec96b.png)
![m6](https://user-images.githubusercontent.com/45032974/80317437-6729d000-880c-11ea-96bc-a6a01c26c2af.png)

**Comment by trendschau** [comment]
Thank you for the contribution! 

The multilanguage-feature is work in progress, some translations are missing because the core-version is still in heavy work and enhances regularly. 

The plugins and theme translations are a separate task, not sure when we will find the time for it but it is on the list...

**Comment by hide-me** [comment]
Ok, thank you for making open-source CMS! I'm glad to support and contribute Russian lang to your project. Hope in next releases you will fix some issues described here.
😃

**Comment by trendschau** [comment]
iusvar added several improvements for translations to version 1.3.6 that has been published today....

**Comment by iusvar** [comment]
Hi trendschau,
the **latest_translations** branch has been excluded, it can be safely combined with the new version137 branch, it makes changes (only three files: en.yaml, it.yaml and vue-shared.js) that concern the hero image in metadata.

To avoid misunderstandings, if and when I make changes I will do it in one branch, meanwhile I have deleted my old branches.

**Comment by trendschau** [comment]
ahh, ok, I did not see that branch, but that is a good strategy: I will merge the latest_translation branch into the actual version branch regularly now and then everything is clean. The merges for version136 worked very smooth and without conflicts, so I think we found a good workflow now!
