### ISSUE TITLE
How to rebuild cache or how to edit files outside Typemill

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#127]
I really like that Typemill uses Markdown files for the content. When I rename some of them including the yaml file Typemill doesn't always see the changes or changes navigation entries to lowercase. That also happens when I put images into the media folder (I've tested the subfolders original and live). Is there a way to rebuild the cache from the files? I already tried to empty the cache folder but that was a bad idea. ;-)

**Comment by trendschau** [comment]
Typemill is not done for that case, you can add files, but renaming files will break the navigation naming and, of course, the url/slug of that page, so it is generally not a good idea. It is generally possible to create a feature that rebuilds the cache for the navigation-names but right now I don't see enough demand for it. The caching is already quite complicated and I don't want to add another layer here right now.

**Comment by Tekl** [comment]
Okay, I understand that it is complicated. My today's learing so far: A flat file cms does not mean you can deal with the files like you want. ;-)

But how do I change the url/slug directly within Typemill? Think of fixing spelling errors or optimizing the slug for search engines or humans.

**Comment by trendschau** [comment]
In those rare cases you CAN change your files manually outside of typemill, the only inconvenience is that you have to rename the navigation (and you should think about it twice because all backlinks for humans are lost and search engines will be irritated, so this is nearly never a good thing for a published and good running website).

This is an edge case with low prio. I follow a clear roadmap with typemill and I won't reach that goal if I handle all edge cases first: https://github.com/typemill/typemill/issues/35

**Comment by Tekl** [comment]
FYI: When I try to rename "datenschutzerklarung.md" to "datenschutzerkla**e**rung.md" then Typemill does not see this change. It gives me a not found error when I click the menu item in the backend. I've to move the entry to another position to let Typemill connect it to the file system again.

**Comment by trendschau** [comment]
First fix is published today with 1.3.7: You can delete now all files in the cache folder and typemill will recreate all cached files including the structure-extended which stores the navigation titles and "hidden" navigation items. 

I did not test intensively, so not sure if it will work in all cases. You might have to hit the f5 button for cache reload more than one time. I will add a button in the author interface as soon as this feature works fine.

**Comment by trendschau** [comment]
done, there is a button in the settings developer area that deletes the cache files.
