### ISSUE TITLE
Retain additional attributes for images

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#128]
When I have an image like `![](media/live/image.png){.icon width=64px}` in my content Typemill will remove the class and width when I select a different image with the visual editor. I think it would be nice that Typemill wouldn't touch this.

**Comment by trendschau** [comment]
added to fixes for next release: 

* If you switch from raw mode to visual mode it will retain (but not display) additional attributes like width and others.
* If you replace an existing image with an image from the media-lib, it will retain the attributes and caption from the old image.

Version 1.3.7 will be published next week probably...

**Comment by trendschau** [comment]
published with version 1.3.7 today.
