### ISSUE TITLE
Add active class to the menu item of a page

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#131]
Currently Typemill only adds the 'active' class to folders in the navigation. When there's a page in the root of my site structure the class is missing. I've tested this with the Emergency and the About me theme. The default Typemill 1.2.4 theme is missing the 'active' class completly. That's different from what I see at Typemill.net where active pages are marked red in the navigation.

**Comment by trendschau** [comment]
good find, that is another side-effect of the hide-page-feature. Will try to fix with next version.

**Comment by trendschau** [comment]
tested this again and it happens only, if there is at least one page hidden. So the solution for hidden pages in navigation worked only partly. 

another find: The breadcrumb for hidden folders is missing.

**Comment by trendschau** [comment]
A fix is published with version 1.3.6. There are still some issues (paging in breadcrumb is not optimal), but it works now generally. Will try to improve with next versions.

**Comment by trendschau** [comment]
BTW: Only standard theme is updated, other themes will follow...
