### ISSUE TITLE
Rights to create a branch

### ISSUE THREAD

**Issue by iusvar** [typemill/typemill#132]
Hi trendschau,
I became a member but I don't think I have the rights to create a branch ...

This is the message that appears to me at the command line:
```
remote: Permission to typemill/typemill.git denied to iusvar.
fatal: unable to access 'https://github.com/typemill/typemill.git/': The requested URL returned error: 403
```

**Comment by trendschau** [comment]
Hi iusvar, I changed the permissions, can you try again if it works now?

**Comment by iusvar** [comment]
Excellent, I just created a branch... thanks

**Comment by iusvar** [comment]
Okay I loaded the branch with the changes I made.

This branch contains:

- the consolidation of some strings both in the language files and in Twig

- cancellation of the getVuejsLabels function (not needed, forgotten the previous time)

- moving the language folders from _settings/languages​​/_ a _system/author/languages/_

- the ability to translate, if the local language is present among those available, even during the installation phase. If this is true the language code is recorded in the settings.yaml file instead of 'en'

- the possibility of translating the strings of the theme (for now only 'typemill') and of the plugins by adding a folder 'languages' in the root of the theme or plugin. The strings of the 'typemill' theme have been transferred to the new files (also for the languages ​​I don't master). Please note: for plugins I only did the job locally, so the 'languages' folders will have to be added together with the language files: in fact if not available the default English language is used

I have only one procedural doubt

To join, do I have to compare and request the pull or can you proceed whenever you want?

**Comment by trendschau** [comment]
Hi isuvar, 

great, thank you! 

Not sure if I understood your last question correctly, but i would propose the following procedure: 

* I pushed the actual version branch version136 to git now: https://github.com/typemill/typemill/branches
* The version branch is the latest state of development and I will push it every day now. 
* It already contains the russian translations from #125 and #126 
* Can you merge the branch version136 branch into your feature-branch and check if everything is fine/without conflicts? 
* If everything is fine I can merge your feature branch back to the version136
* And if version136 is ready I will start the deployment procedure #67 and merge/push all to master and start new branch version137

It is a bit like a simplified gitflow then. 

What do you think?

**Comment by iusvar** [comment]
![image](https://user-images.githubusercontent.com/11983610/80708096-5a96c780-8aeb-11ea-9a49-577e8403bcda.png)

**Comment by iusvar** [comment]
Ok now i18n-1.3.5 contains the changes made with version136...

**Comment by trendschau** [comment]
Ok, perfect, the release is not ready yet, I have to code and fix some stuff before I merge with master and release the version. Beginning of next week I hope :) Thank you!
