### ISSUE TITLE
1.3.5 — Page title not showing on small devices

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#134]
Theme: Typemill
Simulating the visuality via Firefox Dev Tools, the viewports of 768 x 1024, 360 x 740 or 411 x 731 for example, Typemill omitts the page title. This does not happen on typemill.net webpages.

**Comment by trendschau** [comment]
I cannot reproduce this behavior, can you show me a live example?

**Comment by DialogusOne** [comment]
1. Go to https://buchcoach.dmps.de/vorspann/hinweise (Page name »Hinweise«) or subsequent pages
2. Activate in Firefox  ctrl+shift+M Dev Tools Monitor sizes or Vivaldi ctrl+shift+I
3. Page name »Hinweise« omitted

**Comment by trendschau** [comment]
yes, that is the search plugin, will fix

**Comment by trendschau** [comment]
fixed and published with version 1.3.6. In Mobile view the search input is now below the content page.
