### ISSUE TITLE
Find two warnings on error.log

### ISSUE THREAD

**Issue by iusvar** [typemill/typemill#139]
Hi trendschau,
since I often read the Apache error.log file I have noticed two warnings that can be easily resolved.

(Also I'm going to create a new branch with the latest translations)

1. Invalid argument supplied for foreach() in /system/Controllers/MetaApiController.php on line 40
Solution: run only if there are plugins
```
if(!empty($this->settings['plugins'])){
  foreach ...
}
```

2. Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in /system/Settings.php on line 42
Solution: change from
```
$uri = $_SERVER[REQUEST_URI];
```
to
```
$uri = $_SERVER['REQUEST_URI'];
```

UPDATE: Only now after creating this issue, I have a doubt: in cases like these, do you prefer an issue or a branch?

**Comment by trendschau** [comment]
Great, thank you, I fixed it and pushed the new updates to the branch again.

I think in this case an issue is better because a manual fix is easier and quicker then a merge.

The translations work great now!!

**Comment by iusvar** [comment]
I'm happy, you're doing a great job!
