### ISSUE TITLE
Content markdown error in start of a page

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#14]
Most of my pages start with HTML img syntax, then a ### title - but all text on the page is shown in browsers in Bold as a tittle, then the same text shows as ordinary text without Bold. Actually the HTML syntax shows as Bold title too. I'll link to an example later (at work right now)
As it is from your 1.1.7: http://carsten.hedegaard.mobi/opvaekst-mv/frihed
As it is from your 1.2.1: http://121.hedegaard.mobi/typemill/frihed

Oh, by the way: There's a lineshift < br > on top because there's a small problem on mobile phone Oneplus 3T), have to make some distance. And I have to learn to use Twig ;-)

**Comment by trendschau** [comment]
Ok, I see, I will fix it in the next version 2.2.2.

**Comment by carstenwm** [comment]
Oh, okay. Haven't really seen the backend, I'm solely using good old ftp upload of markdown files, that way things work like a dream for me. Or editing via DroidEdit for Android ;-)

**Comment by carstenwm** [comment]
Oh, okay. Haven't really seen the backend, I'm solely using good old ftp upload of markdown files, that way things work like a dream for me. Or editing via DroidEdit for Android ;-)

**Comment by carstenwm** [comment]
Yup, did that ;-)
