### ISSUE TITLE
1.3.6 — On »Notices« compatibility

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#144]
Thank you for adding »Notices«, it surely is an useful addition to typemill. However, the downside »it is not compatible with other markdown processors or editors« moves typemill more or less into the realm of proprietary solutions. Conversation using tools like dillinger.io does not work. Is there no other standardized solution?

**Comment by trendschau** [comment]
There is no standard for notices in markdown. Some widespread solutions are listed in issue #33 and there are probably more individual solutions out there. A standarized way is to use restructured text, but I haven't seen that in any markdown implementation. Another notable way is to use the pandoc-solution but that is not a standard, too (and semantically not nice at all). 

the most widespread solution for notices in markdown is the solution I implemented here and there is one good reason for it: It is semantically clear and easy to understand, it even makes some kind of sense if it is not rendered in html as a notice but as a simple text. And that follows the general markdown philosophy.
