### ISSUE TITLE
TOC Max Lines of Outline –?

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#146]
Is there a maximum number of lines typemill can handle? Just experimenting with the representation of a complex book structure. The TOC is shown correctly, but the following text is cut off. Furthermore, the formatting of the last (possible) head entry is carried on to the previous/next page buttons.

You can see this example currently here: https://buchcoach.dmps.de/prozess/buchprojekt-roman

**Comment by trendschau** [comment]
There are no limitations, but it looks like you use several h1 Elements in one markdown document (which is renderd inside an html-article element) which is not supported by Typemill, at least not a good practice and in this way probably not valid in HTML.
