### ISSUE TITLE
Drag & Drop reordering seems to be broken

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#151]
In Safari the dragging of a page in the sidebar just behaves like dragging a normal link. In Firefox Typemill v1.3.6.2 does show the initial drag, but dropping or reordering has no effect.

**Comment by Tekl** [comment]
In Firefox 68 the reordering works well, in Firefox 76 it doesn't.

**Comment by trendschau** [comment]
Hmm, I use FF 76 in Linux and Windows and it works well, you probably use iOS? That is hard for me to test, I can check if I still have access to browserstack...

**Comment by Tekl** [comment]
I'm using macOS 10.15. In iOS Firefox is just another Webkit browser without the Gecko engine.

But I'm so sorry 🙈. This is no bug. It's caused by the Browser-extension StopTheMadness which I forgot to disable for Typemill. Now it works even in Safari.

**Comment by trendschau** [comment]
That is good to hear !!! 👍
