### ISSUE TITLE
Headline anchor setting is not in sync with settings.yaml

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#152]
In my settings.yaml there is this setting:

```
headlineanchors: true
```

But in the interface the ceckbox is disabled.

**Comment by trendschau** [comment]
Do you have some more details? Because it works fine with my version. Do you update the settings.yaml manually? Please note that "headlineanchors" has the values "on" or null if you change it manually.

**Comment by Tekl** [comment]
Ah, interesting. As the Interface seems to be buggy, I set it to `true` which also works. Using the Interface the value will be set to `'on'` (including the quotes) but after reloading the settings page, the checkbox is still unchecked in v1.3.6.2.

**Comment by trendschau** [comment]
Ok, thank you, i can reproduce it now with an existing typemill-installation, with a fresh installation I cannot reproduce. I will have a look into it...

**Comment by trendschau** [comment]
Published fixes with version 1.3.7 today
