### ISSUE TITLE
Adding new posts does not update the main page.

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#153]
I've the problem that my new posts won't be added to the list of posts. Only the footer on other pages got changed and the left one is pointing to the same post. See here: https://www.tekl.de/news/openthesaurus-deutsch-v2020-05-08

<img width="544" alt="Bildschirmfoto 2020-05-10 um 14 30 24" src="https://user-images.githubusercontent.com/3667947/81499299-e4544b00-92ca-11ea-8abc-b6fb548ce2b2.png">

I had this problem before, but it disappeard and I don't know when. I tried to edit/unpublish the main pages without any effects.

**Comment by trendschau** [comment]
That is only temporary due to the caching mecahnism. The cache refreshs every 10 Minutes. You can refresh the cache manually, just go the page and hit F12 (with windows), not super sure what to do on a mac to refresh a page without cache. Anyway, after 10 Minutes it updates automatically.

**Comment by Tekl** [comment]
Ah, okay. Now it's visible. But at least the pager shouldn't be altered until the refresh, I think. And please add it to the documentation: https://typemill.net/writers/create-pages

Couldn't you add just a small refresh button to the UI? Maybe below of the list of posts (in the backend) -- well, if it only belongs to posts.

**Comment by trendschau** [comment]
These mechanisms are not really supported in V2 anymore because it focuses on users that use the author interface.
