### ISSUE TITLE
1.3.6 — Editing tables in raw/visual mode faulty

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#155]
If adding a table in raw mode and switching to visual mode, an editing is not possible: the editor shows a new 2 x 2 table without the existing structure of cells and rows, which are preserved in the background.

**Comment by trendschau** [comment]
You probably use a different markdown-variant for tables, the visual editor only provides one style.

**Comment by DialogusOne** [comment]
I think both modes should be compatible. Where is the difference (markdown variant) in the following code?

```
| Projekt | Status |
|---|---|
| Aufgaben | |
| Wissen | |
| Notizen | |
```
