### ISSUE TITLE
Meta tab had disappeared on version 1.3.6

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#157]
Hey Sebastian
I tested last version (1.3.6) and I don't find any more the "Meta" tab of articles in admin interface.
The problem arise with commit cb4f2cc99508ff57a7ef6f6c189e22c54e148a6f7 (update to version136)
Moreover, the text of articles in not visible in visual mode.

Olivier

**Comment by oliviercrouzet** [comment]
OK, I understood what happened.
Seems that translations files have changed directory and as the language setting was set on french in my install (a translation file of mine) that did not work. I will try to get my french translation to you  when I update some details.
Olivier

**Comment by trendschau** [comment]
Hi Olivier, yes, we moved translation files to system folder to keep the updates of typemill easier. French translations would be a great contribution!
