### ISSUE TITLE
Translation labels not found

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#158]
Console shows a label = NULL and the content in the visual editor mode gets lost sometimes. Hard to reproduce but probably when language in system settings differ from browser language.

**Comment by iusvar** [comment]
I'll take a look, also because the translation for plugins does not work as it is ...

**Comment by trendschau** [comment]
Great, I already added a fix for the first problem to the version137 branch :)

**Comment by trendschau** [comment]
published with 1.3.7 today
