### ISSUE TITLE
Installation - xxxxx.de/setup fehlt

### ISSUE THREAD

**Issue by marcotheis** [typemill/typemill#164]
Wenn ich die Installationsdateien auf den webserver hochlade, geht hinterher der Setup Link nicht. Wird nicht gefunden ... index.php ist erreichbar, User kann angelegt werden aber das CMS ist dann auch schon "zerschossen"

**Comment by trendschau** [comment]
Sorry, but I cannot help with an error description like that, but I suppose that mod-rewrite is not activated on your server. Please follow the installation guide here: https://typemill.net/getting-started/installation or provide a detailed error description....

**Comment by marcotheis** [comment]
die setup Datei kann nicht angezeigt werden … 

index.php leit auf Index.php/setup weiter

ich kann einen user anlegen - wenn ich mich einlogge kommt aber folgendes:




Marco Theis
Spechtstr. 11b
94535 Eging am See
Funk: 0151 17 66 43 49

eMail: mt@marcotheis.de

**Comment by trendschau** [comment]
Please provide a full error description and read the documentation first. If the issue is solved, then close it.
