### ISSUE TITLE
My preferred working procedure

### ISSUE THREAD

**Issue by iusvar** [typemill/typemill#166]
Hi trendschau,
since latest_translations encounters conflicts while **i18n_on_version137** can be joined without conflict on version137, not being a genius about github, it is more convenient for me:
- make a clone of your latest versionXXX
- make my changes
- create a new branch i18n_on_versionXXX

In this way I am more confident of the changes made that I can test simply.

Tell me if it's okay with you?

**Comment by trendschau** [comment]
Hi iusvar, 

yes, I am not a genius in git workflows, too, and I am still looking for a good strategy (last time I merged some old code somehow, don't know how it happened). 

Your workflow sounds nice, cloning latest version and I will merge your latest i18n back into the version-branch. 

Let us try it that way!

**Comment by trendschau** [comment]
BTW i will update the version with the new frensh translation in the next hour...

**Comment by trendschau** [comment]
Workflow has been described in #167 , I will create a separate ticket that describes the workflow and pin it
