### ISSUE TITLE
Slim Application Error - Typemill 

### ISSUE THREAD

**Issue by JavaMaxi** [typemill/typemill#176]
Hi, ich habe ein Problem: Ich wollte gerade Typemill installieren, hat auch bis zum Setup einrichten alles geklappt, aber wo ich zur Website wechseln wollte, kam nun dieser Error die Details habe ich schon in der Config aktiviert:
Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Message: Call to undefined function Typemill\Models\mb_detect_encoding()
File: /var/www/html/system/Models/Folder.php
Line: 138
Trace
#0 /var/www/html/system/Controllers/PageController.php(296): Typemill\Models\Folder::getFolderContentDetails(Array, Array, 'http://37.157.2...', '')
#1 /var/www/html/system/Controllers/PageController.php(51): Typemill\Controllers\PageController->getFreshStructure('/var/www/html/s...', Object(Typemill\Models\WriteCache), Object(Slim\Http\Uri))
#2 [internal function]: Typemill\Controllers\PageController->index(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/html/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/html/system/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/html/system/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/html/system/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/system/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/html/system/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/html/index.php(7): Slim\App->run()
#12 {main}

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'pathWithoutType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 339

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'pathWithoutType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 339

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'pathWithoutType' of non-object in /var/www/html/system/Controllers/PageController.php on line 328

Notice: Trying to get property 'elementType' of non-object in /var/www/html/system/Controllers/PageController.php on line 339

**Comment by trendschau** [comment]
very sorry about that, all tests passed and tested it manually bit ot seems that some errors got through. I will take a look on Monay evening directly. Is it the git version or the zip downloaded from the typemill website?

**Comment by MasterMaxi** [comment]
Hi, i downloaded the zip file from the typemill website.

**Comment by trendschau** [comment]
Hi Maxi, 

I am back and checked it again but I cannot reproduce that error. I suppose that you run a minimal build-in php-server, right? Are you using Windows or Mac?

On windows I use XAMPP and development + live environment are linux. If you run the build-in php version of Windows or Mac, then make sure that some basic php-libraries are installed. Most important are: 

* mbstring
* iconv
* session
* gd
* fileinfo

If you are not sure, please check your php-version with phpinfo();

Also make sure that htaccess and mod_rewrite are active, but in this case this is not the problem.

I would be happy to get a feedback if this solved your problems

**Comment by trendschau** [comment]
I updated the list of system-requirements in the documentation: https://typemill.net/getting-started/system-requirements

**Comment by trendschau** [comment]
I published typemill 1.3.7.1 with more checks for php-libraries and some improvements, but at the end you have to install those libraries to get typemill running. I tested with build-in php-servers on windows and it works for me.
