### ISSUE TITLE
Any suggestion for a flat file comment system?

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#186]
I came to the point that I want some more interaction on my site. So I thought about adding a comment system. I don't like external providers like Disqus. So I'm looking for a simple self-hosted system. I know about HashOver, but it seems to use a database and is a content managment system by itself. ;-) Maybe someone knows about a more slick php script that fits well into Typemill.

**Comment by iusvar** [comment]
Hi,
googling "Self-Hosted Comment System php flat file", as the fourth proposal, [simplecommentsystem](https://github.com/rosslagerwall/simplecommentsystem), I found a very simple solution.

**Comment by Tekl** [comment]
Thanks. Well, I also found that, but I fear of secuirty issues. It's very old.

**Comment by trendschau** [comment]
I think pytes made a flat-file-comment-plugin for bludit: https://plugins.bludit.com/ I never tried it but it might be a starting point for a Typemill integration.

An alternative idea was to create a plugin for webmentions. Not exactly comments, but a modern rebirth of trackbacks. This is especially popular in the indieweb-community: https://github.com/typemill/typemill/issues/93

Maybe someone in the community finds time, my roadmap is pretty full with extensions for membership, invoices and pdf-generation right now...

**Comment by trendschau** [comment]
Another point: Typemill provides public forms that can be defined with yaml: https://typemill.net/forms/public-forms .This logic should be use by a comment plugin, too. An example of it is the contact form plugin that is not published yet, live demo is here: https://trendschau.net/kontakt

**Comment by Tekl** [comment]
Thanks for the investigation. A comment plugin would be the best solution, I think.

**Comment by trendschau** [comment]
Not on the near roadmap, so I close it for now, would be a good case for plugin contribution.
