### ISSUE TITLE
Notice component removes images

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#187]
When I edit a notice beginning with an image, it disappears after clicking save. The problem is, that the component removes the ! from the image:

`!! ![](media/live/dictionary.png){.left}`

will be replaced by:

`!! [](media/live/dictionary.png){.left}`

**Comment by trendschau** [comment]
I will try to fix it with the next release

**Comment by trendschau** [comment]
fixed in 1.4.0

**Comment by trendschau** [comment]
published with version 1.4.0
