### ISSUE TITLE
Navigation formatting issue

### ISSUE THREAD

**Issue by insintesi** [typemill/typemill#19]
First things first, I'm really glad this exists! Thank you very much for sharing your work with Typemill!

I've encountered a bug that, peculiarly enough, is also obvious on your own page cmsstash.de: In the navigation, the first letter is always in uppercase, whereas the rest is in lowercase. This is particularly irritating in German or if you use abbreviations such as CMS (rendered "Cms").

**Comment by insintesi** [comment]
...this also affects the title shown in e.g. browser tabs: _It's All Capitalized Just Like This._

**Comment by trendschau** [comment]
I have changed this in version 1.2.10, this was an old logic from an early version. Now the lower- and upercase reflects the naming of the files. This might affect existing sites. For now the only possibility to change lower- of uppercase is to rename the files on your server. I will add editing options for navigation item in future.
