### ISSUE TITLE
Support for <kbd> element

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#190]
As Typemill is very good for documentation I miss a way to style keyboard shotcuts like <kbd>⌘⇧4</kbd> in the text. HTML offers the kbd tag but markdown has no equivalent for that.

As the editor does not allow HTML what about a setting to allow some simple tags? Github does also allow `<kbd>`.

**Comment by trendschau** [comment]
I will check it for next release

**Comment by trendschau** [comment]
Not on the roadmap right now, but could probably be added with shortcodes.
