### ISSUE TITLE
link rel="canonical" and meta property="og:*" values

### ISSUE THREAD

**Issue by haraldj** [typemill/typemill#192]
Dear Sebastian Schürmanns,

the <link rel="canonical" href="*" /> as well as the <meta property="og:url" content="*"> and <meta property="og:image" content="*"> tags partly present incorrect information:

https://typemill.net/:
<link rel="canonical" href="https://typemill.net" />
<meta property="og:url" content="">
<meta property="og:image" content="https://typemill.net/">

https://typemill.net/typemill/use-cases:
<link rel="canonical" href="https://typemill.nethttps://typemill.net/typemill/use-cases" />
<meta property="og:url" content="https://typemill.net/typemill/use-cases">
<meta property="og:image" content="https://typemill.net/">

What image should be displayed by og:image?

Kind regards
Harald Jenny

**Comment by trendschau** [comment]
Yes, thank you for reporting, I have to clean it up a little bit. The theme is very new, so not everything is polished, yet. og:image should display the hero image or, if hero is not set, the first image in the article, or, if no image is found, should not appear.

**Comment by haraldj** [comment]
What about the logo image, wouldn't that also be an option as a last resort for the og:image?

**Comment by trendschau** [comment]
yes, good idea to use the logo as last option!

**Comment by haraldj** [comment]
Thanks looking forward to the next release of your very nice program :-).

**Comment by trendschau** [comment]
published with version 1.4.0
