### ISSUE TITLE
login cookie with SameSite=None

### ISSUE THREAD

**Issue by haraldj** [typemill/typemill#193]
Dear Sebastian Schürmanns,

wouldn't it be more secure to make a more strict SameSite cookie value (if this is possible without breaking anything)?

Kind regards
Harald Jenny

**Comment by trendschau** [comment]
yes, you are right, I don't remember if it broke something in the past. I will have a look into it for the next release.

**Comment by haraldj** [comment]
Ok maybe it would break setups where multiple domains use the same CMS (if that is possible...)?

**Comment by trendschau** [comment]
implemented with version 1.4.1

**Comment by haraldj** [comment]
Thanks for implementing this!
