### ISSUE TITLE
possibility to unset headers in system/Controllers/Controller.php and system/Controllers/ContentController.php

### ISSUE THREAD

**Issue by haraldj** [typemill/typemill#194]
Dear Sebastian Schürmanns,

I currently set all the headers you set in these PHP-scripts in my webserver config (and a few more) so I quoted them in the PHP-scripts, how do you think about a config option making these headers removable?

Kind regards
Harald Jenny

**Comment by trendschau** [comment]
Yes, that is possible and a good idea. I will add that configuration to the next release. As this configuration is quite on an expert-level, I will add it only to the settings.yaml-file as another option for devs. Maybe I will add an expert-section in the admin-area in future with some other settings for devs like `displayErrorDetails` and more...

**Comment by haraldj** [comment]
Sounds like a good idea I guess normal users won't need this kind of deep control over Typemill.

**Comment by trendschau** [comment]
postponed to version 1.4.2

**Comment by haraldj** [comment]
Thanks for the information.

**Comment by trendschau** [comment]
published with 1.4.2, please reopen if you find any problems

**Comment by haraldj** [comment]
Will do but it seems everything works, thanks.
