### ISSUE TITLE
unable to install 1.3.8

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#195]
Hello Sebastian,

I tried unsuccessfully to install last version on a Debian Buster vbox. I made a fresh install  with git clone + composer update.
At first connexion on the browser, I got a "Slim Application Error". The _settings_ directory is not event created.

The following error is to be seen in apache logs:
`Slim Application Error:\nType: ParseError\nMessage: syntax error, unexpected '?', expecting variable (T_VARIABLE)\nFile: /var/www/typemill/system/vendor/twig/twig/src/Node/Expression/GetAttrExpression.php\nLine: 20\nTrace: #0 /.`

and so on...

Don't know if I missed something...

Olivier

**Comment by trendschau** [comment]
Hello Olivier, 

that is strange! Indeed, the settings folder is missing, but should be create on first call. I just tested a fresh install with git clone + composer update on my local windows machine with xampp and it works without any errors, no errors in apache error logfile either. So maybe it depends on your environment with debian. 

Unfortunately I can only test on my local windows and my local linux machines, I don't have a live server with git- or composer-access, so I only use the zip-version for productive websites. Do you have the possibility to test it with another environment or on your local machine?

**Comment by oliviercrouzet** [comment]
Well, the thing I missed was that the php version enabled on my vbox was 7.0. 
I made an update from Debian Stretch sometime ago and I suppose that I have forgotten to enable 7.3. 
The syntax with a question mark preceding a variable type have been introduced in php7.1 (Google told me). That's why I got this error.
With 7.3, it's OK
Sorry to disturb you for nothing
Olivier

**Comment by trendschau** [comment]
Ahh, ok, thank you, looks like some libraries upgraded the minimal PHP-version. I updated it in the documentation to 7.1+
