### ISSUE TITLE
Best practice for cache busting?

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#201]
To give my visitors always the newest CSS file, I add a query string the file name:

```HTML
<link rel="stylesheet" href="{{ base_url }}/themes/emergency/style.min.css?v=1" />
```

So the Browser will force loading the new file instead of using the cache. See here for more details: https://css-tricks.com/strategies-for-cache-busting-css/

What would be the most performant way to add an automatism to my theme which will change the query string every time I update the CSS file? At the moment I alter the twig file manually.

**Comment by trendschau** [comment]
I do that manually, too. You can probably automate it with a build-process, but that means that you have to create that build process first. As far as I know, webpack has a feature for that, but I do not work with webpack or other frontend-packaging software. 

I also use url-params for this, but the cleaner way is changing the url itself (I don't remember the details, but url-params can break the cache in some situations when it does not make sense). 

I think Google has some informations about it ("url-fingerprinting"), they link to this article: https://web.dev/http-cache/#response-header-strategies

**Comment by Tekl** [comment]
As I don't like build processes for a simple project and because I update my website also on the go with my smartphone I'll stay with the manual naming. 

Thanks for mentioning the caching issues with query parameters. Now I add the version number to the name. Well, I don't want to create new named files, so I use the following mod_rewrite rule to redirect the special names to the same file:

`RewriteRule ^(.*)-([0-9]+).(js|css)$ $1.$3 [L]`

If the file is named `style.css` I can write `style-123.css` in my template and it will load `style.css`

**Comment by trendschau** [comment]
Clever solution, thank you for sharing!
