### ISSUE TITLE
(Optional) use of original images without scaling

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#203]
When I upload images in Typemill they are scaled down to this value in the settings:

```yaml
images:
    live:
        width: 820
```

Most time the image files will be bigger then my original ones which are bigger but highly compressed with the tool ImageOptim. At the moment I just overwrite the image files in the live folder the ones from the original folder.

Can I setup Typemill to always use the original images (mostly screenshots)? I know that they have more pixels than they use in the content. But the browser scaling produces much sharper images and the images are looking good on HiDPI screens as well. And as they are smaller in size than TMs scaled images, the visitor doesn't have any disadvantages.

**Comment by trendschau** [comment]
Can you try to increase the value manually to a very large size like 3000 or something like that? I don't remember exactly but Typemill does not resize/change the image if it is smaller than that size, so the live images will be the same as the original images.

I plan some "developer"-configurations in the admin area for next release so I could make that value editable there.

**Comment by Tekl** [comment]
Thanks for your answer. Increasing the value has no effect. The screens will be resized to 820 px width. Is this setting cached anywhere?

**Comment by trendschau** [comment]
I don't think so, but not sure because I completely refactored the image handling with version 1.3.7. 

Can you attach one of your images here? Then I will check it before next release in mid september

**Comment by Tekl** [comment]
This is the one of the screens I've tested (it's not preprocess by ImageOptim yet).

<img width="528" alt="Bildschirmfoto 2020-08-13 um 17 44 35" src="https://user-images.githubusercontent.com/3667947/90653634-b6729100-e23f-11ea-838f-21f8313da383.png">

**Comment by trendschau** [comment]
Published with version 1.4.0. In the developer settings you can add a standard with and standard height for images in the content area now. If the width in the settings is higher than the width of the image, then it will not be resized. This way the images in the live folder should be the same as the images in the original folder.
