### ISSUE TITLE
Left menu : Special Characters are not allowed. Length between 1 and 20.

### ISSUE THREAD

**Issue by jmlauranson** [typemill/typemill#22]
I am admirative and very supportive to typemill, such a great tool !

It would be great if the left menu labels could accept Special characters such as numbers and accents and if it couls be extended to more than 20 characters.

For example, I would like to be able to display the left menu as follows:

3. COMMENT FINANCER SA VAE ?
3.1 etape 1
3.2 Qui contacter
3.3 Être admis
3.4 Rédaction
3.5 Relecture
3.6 Soutenance VAE

4. ÉTAPES DE LA VAE
4.1 Orientation
4.2 Qui contacter
4.3 Être admis
4.4 Rédaction
4.5 Relecture
4.6 Soutenance VAE

Is that feasible?

Thanks a lot for the hard work and all the best for the future of typemill !!!

Best Regards,
JM LAURANSON

**Comment by trendschau** [comment]
I just published the version 1.2.10 so I can add this to the next version 1.2.11 that will be published in 2 or 3 weeks. This is what I can change: 

* Allow up to 40 characters
* Allow numbers and some limited special-charackters like `.` and `?` and `!`
* Special chars for languages like `Rédaction` are possible already, but depends a bit on servers, so might produces errors sometimes.
* I will add an option for the theme to display chapter-numbers like `1.2` automatically in the navigation (only frontend). In fact Typemill already adds theses numbers, but I did not add them to the theme/navigation yet. I think automattic numbers are much more convenient than writing (and correcting) the numbers manually. The counting is part of the [`$item`-object](https://typemill.net/theme-developers/theme-variables/item#itemchapter)

BTW, it is planned to make the navigation-items editable in future, but I don't know when I will find the time for that feature. It is probably be better done by meta-data, which is a bit more complex, so round about march I suppose ...

Best regards
Sebastian

**Comment by trendschau** [comment]
If you do not want to wait for the next release and add the chapter-numbers yourself, then you can simply change [this theme-file](https://github.com/typemill/typemill/blob/master/themes/typemill/partials/navigation.twig) a bit: 

````
{% macro loop_over(navigation) %}

    {% import _self as macros %}

    {% for element in navigation %}
	
		{% set depth = element.keyPathArray|length %}
		
        {% if element.activeParent %}
			<li class="{{ element.elementType }} level-{{ depth }} active parent">
		{% elseif element.active %}
			<li class="{{ element.elementType }} level-{{ depth }} active">
		{% else %}
			<li class="{{ element.elementType }} level-{{ depth }}">
		{% endif %}
            {% if (element.elementType == 'folder') %}
				{{ element.chapter }} <a href="{{ element.urlAbs }}">{{ element.name }}</a>		
                <ul>
                    {{ macros.loop_over(element.folderContent) }}
                </ul>
            {% else %}
				{{ element.chapter }} <a href="{{ element.urlAbs }}">{{ element.name }}</a>
            {% endif %}
        </li>
    {% endfor %}
{% endmacro %}

{% import _self as macros %}

<ul>
    {{ macros.loop_over(navigation) }}
</ul>
````

so simply add `{{ element.chapter }} ` in front of the navigation item of the theme...

**Comment by jmlauranson** [comment]
Thanks a lot for this lightning fast answer and solution provided. I will try it. 

Have a wonderful week.

**Comment by trendschau** [comment]
This feature is live now with version 1.2.11, so I will close this ticket :)
