### ISSUE TITLE
cannot delete folder or file, cannot save after typing

### ISSUE THREAD

**Issue by hasu4p** [typemill/typemill#23]
![delete](https://user-images.githubusercontent.com/16002293/52485238-65abc200-2bde-11e9-80d0-ddd1bc1e3163.JPG)
cannot delete folder or file. cannot save after typing. the spinner keeps spinning. using php 7. have access to .htaccess and mod_rewrite. how to fix it?

**Comment by trendschau** [comment]
Did you make the folders on your server writable like described here: https://typemill.net/getting-started/installation ?

**Comment by hasu4p** [comment]
Yes 774 permission set to all folders and subfolders. But the problem remains. I am using hosting services of infinityfree, which offers php7. When I ran your program in a local server vertigo with PHP 7.1 it runs flawlessly. Please suggest tweak for running it on php7.

**Comment by hasu4p** [comment]
I can create folders and files, but I cannot save and delete.

**Comment by trendschau** [comment]
I will check it tomorrow with php7. Maybe you can check the response from the server when you save? open dev tools of browser (f12), go to network, then click the save button and check the response for the post-request. If there are errors then it helps fixing. Thank you

**Comment by hasu4p** [comment]
![2](https://user-images.githubusercontent.com/16002293/52521643-07471800-2ca0-11e9-98c3-c195757ec0de.JPG)
![3](https://user-images.githubusercontent.com/16002293/52521644-0c0bcc00-2ca0-11e9-8986-29df755bfba9.JPG)

**Comment by hasu4p** [comment]
![4](https://user-images.githubusercontent.com/16002293/52521657-70c72680-2ca0-11e9-9ca5-d8e83a6a9cfc.JPG)

**Comment by trendschau** [comment]
sorry, I can't help here quickly, it is not visible what happens in the background. However, I never tested a subfolder installation with nginx, so maybe there are some errors. Should not be related to php7. Your server tries to return some error page that fails because of cors, but this is probably not the reason for the error initially. I will try to investigate more, but I don't have a quick solution for it now. Sorry....

**Comment by hasu4p** [comment]
Thanks for your response, and the wonderful software. I've tested many. Your software is probably the best right now! If you find some time, please test it on infinityfree.net. They provide free web hosting and php 7. In the meantime I will try to figure it out.

**Comment by trendschau** [comment]
Hi hasu4p, I tested typemill with php 7.0 now and it works, so this is probably a problem with nginx or the hoster. I am not a nginx-expert, so hopefully someone else of the github-followers can help here. I will keep this ticket open for now.

**Comment by trendschau** [comment]
I will close this ticket because it is one year old and not really related to typemill, but to the hosting environment. Please reopen if it is still relevant.
