### ISSUE TITLE
favicon missing since release 1.4.0

### ISSUE THREAD

**Issue by haraldj** [typemill/typemill#232]
Dear Sebastian,

with the new release the favicon is not displayed anymore, could you please have a look at this? Seems like some apple-touch-icon lines with the sizes 72x72, 114x114 and 144x144 are missing from the output.

Kind regards
Harald Jenny

**Comment by trendschau** [comment]
thank you, I will have a look. Do you use the theme Cyanine?

**Comment by haraldj** [comment]
No I use aboutme but I installed cyanine now and it seems this somehow fixed the problem also when going back to aboutme the favicon is displayed. Nontheless, the three image lines are not there anymore is this a bug or on purpose?

**Comment by haraldj** [comment]
I tried the latest version of aboutme (due to a local problem it didn't display a message) and this fixes the lines problem I will try to set up a completely new instance when I have time to confirm that there are really no bugs left.

**Comment by haraldj** [comment]
Ok I guess this was a strange issue due to upgrading at least with a new installation it works flawlessly so closing this bug report.

**Comment by trendschau** [comment]
I am glad to hear that!

**Comment by haraldj** [comment]
Me too and sorry for the noise.
