### ISSUE TITLE
File-Upload changes files

### ISSUE THREAD

**Issue by pkaltenboeck** [typemill/typemill#236]
We provide some xlsx and txt to download, they were uploaded using the File-Upload Form in the VisualEditor unfortunatley the upload seems to add the content-type to the end of the file:
![image](https://user-images.githubusercontent.com/1273655/100894639-fe4eb880-34bc-11eb-9ae8-98699af8cb3f.png)

This causes some Problems depending on the file we are uploading, xlsx - Files can't be opened, Code-Snippets are not working.

**Comment by trendschau** [comment]
thank you, merged for next release 1.4.3

**Comment by trendschau** [comment]
published with 1.4.3 today
