### ISSUE TITLE
* Old title JSON Parse Error -> how to setup with mod-security2?

### ISSUE THREAD

**Issue by ThSeyfarth** [typemill/typemill#243]
Hello dear Mates,
today i installed typemill to my VM and setting up like your Wizard shown. But now if the First User (it might be the Admin) tries to upload a File or tries to delete or something like that we'll get an 403 Error.

In the Console Log stood:

XHR PUT https://****.****.com/api/v1/image                              [HTTP/1.1 403 Forbidden 28ms]

Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data           vue-blox.js:327:25
    
saveBlock https://****.****.com/system/author/js/vue-blox.js?20210108:327
onreadystatechange https://****.****.com/system/author/js/author.js?20210108:66
sendJson https://****.****.com/system/author/js/author.js?20210108:60
saveBlock https://****.****.com/system/author/js/vue-blox.js?20210108:315
VueJS 34

Ive took a look at the permissions on www-Folder but here's like the Wizard meant (Folder 755, Files 644). What did missed? Hope anyone can help me out for this issue.

Thank you for fast helps

best regards 

Thomas

**Comment by ThSeyfarth** [comment]
@Update 
I need to revoke my further Message. It seems like it is a Problem with Settings at Mod-Security. 
I ve installed mod-security2 and activated and was setup the Config File for higher sizes as 128Kb.  Now mod-security working well, but cant still upload Files. Something i need to adjust.

**Comment by trendschau** [comment]
thank you for your message, I just tested it on my installation and it works fine for me. I am not familiar with mod-security. Maybe you have to add mime-types? Typemill does also check mime-types, so for some files it might reject an upload.

**Comment by trendschau** [comment]
BTW: If you use NGINX for Typemill, it would be a highly appreciated contribution to share your NGINX setup for Typemill. I don't use NGINX, but many users ask about an nginx-guide for Typemill :)

**Comment by ThSeyfarth** [comment]
I will close this Issue. I handled it with Nginx and it worked very well. Thank you Trenschau.
