### ISSUE TITLE
"Please check your input and try again" 

### ISSUE THREAD

**Issue by thecenters** [typemill/typemill#244]
Every time I try to create an account I get this error. I get no other validation errors.

![image](https://user-images.githubusercontent.com/1264853/106051800-c10e3d80-609d-11eb-9a85-733ab8d5d9f3.png)

**Comment by trendschau** [comment]
Thank you for reporting. Can you please check if your settings-folder and inside the folder "users" are writable?

I will try to reproduce that locally.
