### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by ThSeyfarth** [typemill/typemill#247]
Hello Trendschau,
since ive been running the last update to 1.4.4 i got some trouble with the Certificate handelings. Sometimes is my certificate accepted as secure sometimes not. It almost happend when ive been logged in. Can it come from the new user management?

I dont use letsencrypt. My Certificate issuer is Sectigo. 

Your Setup Typemill Movies at youtube are awesome. Many thanks for it

Best regards

Thomas

**Comment by trendschau** [comment]
Hi Thomas, 

thank you for the feedback! 

Regarding the certificate: I don't think that this is a Typemill issue, at least I am not aware of any code that might affect it. I suppose it is an issue with the certificate itself, with the hoster or with the browser. You could check the certificate for errors here https://www.sslshopper.com/ssl-checker.html or here https://www.digicert.com/help/ , you can also search for browser issues with certificates and if that not helps, maybe contact the hoster?

Best regards
Sebastian

**Comment by trendschau** [comment]
Hi Thomas, 

I will close this issue because probably not a typemill issue. Thank you, Sebastian

**Comment by ThSeyfarth** [comment]
Yeah thank you Trendschau, 
sorry for my late answering. It was my failure with these Problems. Was a Setup Problem in my Config-Folder on my Web Server
