### ISSUE TITLE
Metadata tab is only showing in visual mode

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#250]
Hello Sebastian,
I am testing an update to 1.1.4 with Typemill theme and I find out that in raw mode editing, the metadata tab does not show any more. I tried with cyanine theme : the same.

Olivier Crouzet

**Comment by trendschau** [comment]
Hi Olivier,

thank you for reporting, it will be fixed with version 1.4.5

**Comment by trendschau** [comment]
1.4.5 has been published today, it should work now again
