### ISSUE TITLE
Markdown Includes

### ISSUE THREAD

**Issue by saidsl** [typemill/typemill#254]
Hello

Is there anyway or has anyone tried or created a Markdown Include Plugin

Use case: on most sites there is content that is used in a number of place (not footers or headers). So it would be very practical to include content from another markdown file into another file. This way when making changes or updating, we don't have to search in multiple places. 

Thank you.

**Comment by trendschau** [comment]
Not as far as I know. There are probably several ways to do it, but I am not sure if there is a clean way without touching typemill core. I won't have time in the next month but it might be an idea to enhance Typemill with shortcuts to hack into the content like this...

**Comment by trendschau** [comment]
Just as a reminder for me to implement shortcuts e.g. in version 1.4.10: 

* enhance parsedown library
* search for syntax like [:myshortcut:] or similar in blocks and inline when array is transformed into array
* foreach location fire a new event and pass over the shortcode
* plugin can then replace shortcut with any kind of raw-html. 
* question is what to do with it in ebook production (strip out or parse).

**Comment by trendschau** [comment]
You can realize a markdown-include with the new shortcode-feature of version 1.5.1 now. There is a short documentation here: https://typemill.net/plugin-developers/shortcodes

**Comment by saidsl** [comment]
@trendschau, That is awesome, thank you soo much for this update. Look forward to testing it out
