### ISSUE TITLE
Feature request: changelog/history of changed pages

### ISSUE THREAD

**Issue by thenktor** [typemill/typemill#256]
Hi,

it would be nice if there would be the possibility to show recent changes on pages, just like Dokuwiki, e.g. https://www.dokuwiki.org/dokuwiki?do=revisions

Another nice idea for this is something like this: https://getgrav.org/blog/git-sync-plugin (did not test this, but it seems it syncs all changes to pages to a git repo).

**Comment by trendschau** [comment]
thank you for your feedback! 

yes, both features have been discussed with other users and are on my roadmap, but I don't know when I will find time for it, I hope until end of this year. First feature is some kind of versioning and could/should also be done with a plugin to keep the core code lean...

**Comment by thenktor** [comment]
Just watched a video about this Grav git-sync and IMHO that's indeed even cooler than a self-made versioning: https://www.youtube.com/watch?v=3fy78afacyw

Maybe something to consider 😉

**Comment by trendschau** [comment]
Yes, that looks cool, especially for developers who use GitHub. In discussions with users it turned out that not all users want to use github, so there shoud be another option for versioning without GitHub or other dependencies. But it makes totally sense to start with GitHub Sync, it has probably much less overhead.

**Comment by trendschau** [comment]
Both is planned for Typemill version 2 as paid plugins. Since most clients work without github integrations, I will first provide a self-made versioning plugin and it is planned for Q1 of 2024.

**Comment by trendschau** [comment]
I will close this ticket because we have questions/answers on github now so I will only keep bugs open and features that are in development.
