### ISSUE TITLE
Css Validation

### ISSUE THREAD

**Issue by ironmaid3n** [typemill/typemill#257]
Hello, in style.css line 370 delete  font-smoothing: antialiased; to make pass valid the css on https://jigsaw.w3.org/css-validator
Version 1.4.5
Thanks

**Comment by trendschau** [comment]
Thank you for reporting, but unclear where (theme?) and don't find it anymore. There are quite some errors in css-validator. Might be part of a theme rework in future. Typemill itself works with Tailwind and has nearly no own styles anymore.
