### ISSUE TITLE
Unsaved changes get lost while changing from raw mode to visual mode

### ISSUE THREAD

**Issue by thenktor** [typemill/typemill#258]
Hi,

in the page editor unsaved changes get lost when changing from raw editor to visual editor.
There should at least be a warning.

**Comment by trendschau** [comment]
agree, there is no autosave, I can add that to the next release...

**Comment by trendschau** [comment]
implemented alert box when there are unsafed changes for release 1.4.6...

**Comment by trendschau** [comment]
btw the upcomming release with recent changes is available in develop-branch: https://github.com/typemill/typemill/tree/develop . Still not sure when 1.4.6 will be published.

**Comment by trendschau** [comment]
1.4.6 published now.
