### ISSUE TITLE
Page Toolbar does not appear for editors if on a page they did not create

### ISSUE THREAD

**Issue by adioni** [typemill/typemill#263]
Experiencing an issue where editor accounts' web interface isn't displaying the toolbar when editing pages they themselves did not create. I'm on version 1.4.6.

[Example Screenshot of Issue](https://imgur.com/a/J8Oj91k)

**Comment by trendschau** [comment]
good find, thank you, it is a very stupid bug/simply fix, because I checked for the right "edit", which does not exist, it should check for "update". I will create a hotfix for it and publish it in the next days...

**Comment by trendschau** [comment]
published the fix with version 1.4.6.1
