### ISSUE TITLE
Bug in theme Cyanine, version 1.1.5

### ISSUE THREAD

**Issue by sopkomir** [typemill/typemill#266]
Hello, function add images to list of blogposts is not correct, only from last post, but black images were created for all others.

look link: https://test.eduvolucia.sk/novinky

**Comment by trendschau** [comment]
thank you, I will have a look into it and fix it for next version. If you need it urgently, then you can use the develop-version when the fix is ready, I will provide a link to it then. 

BTW: looks really beautiful that website!! 👍

**Comment by sopkomir** [comment]
> thank you, I will have a look into it and fix it for next version. If you need it urgently, then you can use the develop-version when the fix is ready, I will provide a link to it then.
> 
> BTW: looks really beautiful that website!! 👍

Thank you, original website is https://www.eduvolucia.sk/ :)

**Comment by trendschau** [comment]
sorry for the delay, I fixed it in the develop branch now and will ship it with upcomming version 1.4.7. Feel free to use the version in develop branch in the meantime.

**Comment by trendschau** [comment]
fixed with cyanine version 1.1.6 and typemill version 1.4.7 (just published)
