### ISSUE TITLE
Support for categories and/or tags?

### ISSUE THREAD

**Issue by dink** [typemill/typemill#270]
Very nice little CMS!

I'd like to know if there are any plans to include categories and/or tags along with posts, as that sort of thing is a must-have for any reasonable blog engine?

**Comment by trendschau** [comment]
Thank you very much!

Yes, there are plans for tags, probably until end of this year, but keep in mind that Typemill is not a blog engine, so blog features will always play a minor role.

**Comment by trendschau** [comment]
there is a kind of category/tag-plugin now, but it differs from the usual tag-concept of other systems. See plugin here: https://plugins.typemill.net/tagfilter and a live example here: https://cmsstash.de/empfehlungen/cms-finder
