### ISSUE TITLE
How to list related content below a page

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#271]
I've added a field category to the metatabs. How can I list all articles in the same folder which have the same value for that field? Something like `item.thisChapter.folderContent` does not seem to exist.

**Comment by trendschau** [comment]
Not sure if I totally understand your requirement: If you are on a "folder" page that contains sub-page, then you have access to all sub-pages with `item.folderContent`. You can list the pages of that folder like that (implemented in several themes): 

```
	{% for element in item.folderContent %}

		{% set post = getPageMeta(settings, element) %}

		<li class="post-entry">
			<header>
				<a href="{{ element.urlAbs }}"><h2>{{ post.meta.title }}</h2></a>
			</header>
			<p>{{ post.meta.description }}</p>
		</li>

	{% endfor %}
``` 

You can also query the category of the post with an if statement there. Not sure if that is enough for your case.

For a real category or tag feature, you have to create a plugin that creates an index file with all categories/tags and all pages, so it is a bit more complicated. Such a plugin is on my roadmap, but I won't find time in near future/this year.

Hope that helps?

**Comment by Tekl** [comment]
Thanks alot. For a folder I already know how to get the subpages. I want to access the folderContents when I'm viewing a single file.

**Comment by trendschau** [comment]
Ah, ok, makes sense. This.chapter has no folder content, it is only for paging and adding the folder-content would blow up the object in many cases.

But it should still be possible with the navigation and the getPageList-method. I have to check it when I find time, but it should work like this:

```
  {% set pagelist = getPageList(navigation, urlToFolder, base_url) %}

```

urlToFolder should be something like item.thisChapter.urlRel

Will check it in the next days and answer here.

**Comment by Tekl** [comment]
Hi and thanks again. That was very helpful. I already found the Function getPageList in the Twig docu but it seems to behave different in Typemill. This code seems to work:

```twig
{% if item.thisChapter and metatabs.meta.category1 is not null %}
	{% set pagelist = getPageList(navigation, item.thisChapter.urlRel, base_url) %}
	<h4>Related content for {{ metatabs.meta.category1 }}</h4>
	<ul>
	{% for element in pagelist.folderContent %}
		{% set post = getPageMeta(settings, element) %}
		{% if post.meta.category1 == metatabs.meta.category1 or post.meta.category2 == metatabs.meta.category1 %}
			<li>
			<a href="{{ element.urlAbs }}">{{ post.meta.title }}</a>
			</li>
		{% endif %}			
	{% endfor %}
	</ul>
{% endif %}
```

**Comment by trendschau** [comment]
glad you found a solution!
