### ISSUE TITLE
Rename blog posts

### ISSUE THREAD

**Issue by thenktor** [typemill/typemill#272]
Hi,

it is not possible to rename blog posts.

I'v tried to change all 3 title fields (title, meta title, navigation title) but none affects the actual file name on the disk and therefore also the link. So if I've initially made a mistake in my blog post title I'm now stuck with a weird link to the blog post.

**Comment by trendschau** [comment]
Yes, that is not possible right now. That feature can be implemented in a future release, but it should be clear to editors, that it will change the url and thus kick out the original page from the index of search engines, so for a content-driven website this is highly critical.

**Comment by thenktor** [comment]
Of course this breaks links from search engines, but my use case is changing a link/title, that has typos or that had a temporary name. Usually you notice this kind of stuff long before the page was indexed.

**Comment by trendschau** [comment]
yes, as soon as I find time for it, I will add it to core ...

**Comment by trendschau** [comment]
This will be part of next release 1.4.9

**Comment by trendschau** [comment]
Slug rewriting is published with version 1.5.0 now: https://typemill.net/news/version-1-5-0-rename-slugs
