### ISSUE TITLE
Blog-Posts on Homepage (question)

### ISSUE THREAD

**Issue by ssch1124** [typemill/typemill#276]
I am using Typemill for a small project atschool and wanted to know if it is easily possible to show blog posts (all from one folder) directly on the home page, like it is on cmsstash.de for example. 

I couldn't find anything concerning that topic in the documentation and spontaniosly I have no idea which kind of trick or code snippet I need for realising it. Does this functionality depend on the theme? 

Thanks for the help and greetings from Germany! :)

**Comment by trendschau** [comment]
Thank you, I am happy to hear that! 

You can do that kind of blog-posts on the start page with the Cyanine theme like this: 

* Create a folder in the content area, let's say "blog"
* Go to the meta-tab of the new folder and activate "posts" (at the bottom). 
* Create some posts
* Go to the theme-settings and make the following settings:
  * activate the list of posts on the homepage
  * optionally activate the content before the post-list (it will show the content from the folder, you can also skip that)
  * add the folder name "/blog"
  * deactivate the landingpage
  * Optionally you can configure the design of the post-list as cards with hero-images.

Here is a screenshot from the settings that I used for cmsstash:

![grafik](https://user-images.githubusercontent.com/2714547/128071717-2683d1da-3770-4e10-8b53-bce1ab9fce0e.png)

**Comment by ssch1124** [comment]
Thank you. That's the solution I searched for! 

(And it explains why I could not get it to work with the "typemill" theme. Maybe it would be a nice feature for core?)

**Comment by trendschau** [comment]
yes, you are right, that would be a nice feature for all/many themes, but it has to be implemented individual for each theme. 

Unfortunately I don't have the time to maintaine all themes, so I hope that other developers will take over one or two of them and maintain / refactor them. Especially the typemill-theme is pretty popular but the code base is a bit old, so it could be refactored and extended with the many new features that the cyanine theme already implements.
