### ISSUE TITLE
Some problems after update to 1.4.7

### ISSUE THREAD

**Issue by edlefs** [typemill/typemill#277]
After many years with Wordpress i find Typemill very appealing and have just been taking my first steps with it for a few days. Now I have a few problems with the update.

After the update to 1.4.7 (I simply overwrote all files from the zip)
Should I have done it differently?

- In the backend all words in the navigation are now in lower case only
- The names of the posts in the frontend menu are now completely in lower case letters
- The umlauts in the menu are no longer present (Bucherei instead of Bücherei)
- The contents of the **Startpage** and the page **Welcome** are overwritten with the standard Typemill texts

Further Problems:
Image upload partly not possible (all png), the image appears, the corresponding dialogue box is not loaded, the loading symbol circles endlessly. Could it be the image?  It works with some images, not with others, the image sizes are all under 800kB.

Some images (png) can be loaded without problems, others not, but this was also the case before the update...

What is the "blox-editor" or is that a typo in the latest news?

TIA

**Comment by trendschau** [comment]
Thank you, I am glad to hear that you like Typemill. 

Regarding Updates: In nearly all cases a minor update is enough. Like described in the documentation you only have to updated the System-Folder (and the corresponding theme folder): https://typemill.net/getting-started/update

The ZIP-File contains a complete typemill website with demo-content, so if you have simply overwritten all files from the zip-files, then some content files are overwritten, too. 

If you face any problems with lowercase and uppercase, then the cache files have been deleted or are not accessible anymore. You can delete the cache with the button in the settings (developer settings). The cache is recreated when you visit a frontend-page. 

The "blox-editor" is the visual block editor (vs. raw editor). 

Images: Can you attach an image here that does cause the described problems? I had to change the image upload a bit to close a security hole (https://github.com/typemill/typemill/issues/268). Maybe your images have a wrong mime-type (this can happen if you rename a jpg-image to  a png-image, for example).

**Comment by edlefs** [comment]
Thank you very much for the quick reply!
- I should have guessed about the update, I never stop learning :-)
- Clearing the cache fixed the error with the umlauts and the lower case letters, thanks!
- I'll test the pictures again and then upload one. 

Now I'll keep testing, thanks!
