### ISSUE TITLE
Chapter numbers in overview

### ISSUE THREAD

**Issue by LiohMoeller** [typemill/typemill#28]
It would be great to have an option to display also the chapter numbers in the overview, like on the startpage. Right now there are unnumbered buttons, and from the logic it reads from left to right and then the next row, which is not so obvious on the first sight. Having an option to add chapter numbers there as well, would make it easier to clearly identify chapters and subchapters.

**Comment by trendschau** [comment]
Hi Lioh, that should be easy, I will add it to the next release, but I don't have a fixed date for the next release yet ...

**Comment by trendschau** [comment]
Hi Lioh, this is now integrated with the recent Version 1.2.16, I activated it for the typemill website https://typemill.net
