### ISSUE TITLE
Bugs regarding the 1.3.0 ebooks plugin

### ISSUE THREAD

**Issue by MysterieDev** [typemill/typemill#280]
After updating i've encountered following error:

![grafik](https://user-images.githubusercontent.com/32373099/131250957-188c17dc-b996-4774-afa7-77ef28fe9d38.png)

before updating ebooks, i made sure to copy 1.4.8s system folder to my installation, as the update-guide describes.

I think paged js has a problem with my content for some reason

**Comment by MysterieDev** [comment]
![grafik](https://user-images.githubusercontent.com/32373099/131251033-b09246c6-e805-4d22-a969-744c8f93a084.png)
 i've also encountered multiple vue errors, this also happens generating an uuid for epub

**Comment by trendschau** [comment]
thank you, I will try to fix them for the next release.

The first error looks like firefox, it should work in chrome correctly. It occures in firefox if the table of contents spans over two or several pages. Not sure why exactly it happens and not sure if the team from paged.js can help here. I will investigate.

**Comment by MysterieDev** [comment]
@trendschau i've checked on my MacBook + Chrome (Chromium) and i've gotta admit, that i get a working result there (yay)

It kinda wonders me though. I've also tried it on Edge (Chromium) but that didn't seem to work either.

**Comment by trendschau** [comment]
Yes, Edge does not work, they probably have a different implementation than chrome. Anyway, I am not sure if this errors are caused by page.js or if the script for the table of contents is wrong in some way. Have to investigate. Despite of that, I always use chrome, because it delivers the most reliable results when generating publications.

**Comment by trendschau** [comment]
I fixed the error with table of contents in Firefox, it was caused by css styling, I will publish it with the next release.

**Comment by trendschau** [comment]
Hm, I fixed this bug but got other bugs depending on the content structure and not related to the table of contents script. I think Firefox is simply not reliable for paged.js, but I will open a ticket there if problem like this are known.

**Comment by MysterieDev** [comment]
maybe (just an idea) you could make a javascript call to the user agent and display a disclaimer for browsers unlike chrome that the plugin does not guarantee to work on these browsers!

**Comment by trendschau** [comment]
Good Idea and implemented in version 1.3.1 :) 

I will open an issue to paged.js about the problems with firefox.
