### ISSUE TITLE
Session cookie 'login' is not set? 

### ISSUE THREAD

**Issue by robo-wg** [typemill/typemill#282]
Hi,

There is an if query in the layout.twig (themes\cyanine) file:

```
{% if is_loggedin() %}
   ...
{% endif %}
```

In the file TwigUserExtension.php (system \ Extensions) there is also a corresponding "reference" or a function. 

```
public function isLoggedin()
{
	if(isset($_SESSION['login']) && $_SESSION['login'])
	{
		return true;
	}
	return false;
}
```

**But the session cookie "login" is never set for me.** 

---

Also, the svg in the layout.twig (themes\cyanine) is never shown:
```
<svg style="position: absolute; width: 0; height: 0; overflow: hidden" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">...
</svg>
```

I'm just getting used to typemill and can't find an answer to that myself. Request for Help.

**Comment by trendschau** [comment]
Typemill does not use cookies in frontend by default (for users who want to avoid any kind of cookie). 

You can activate cookies in frontend as a kind of sideeffect, if you go to -> settings -> access control. Just activate the "page restriction" and cookies will be set on all frontend pages.

**Comment by trendschau** [comment]
I will close it for now to focus on issues with bugs.
