### ISSUE TITLE
variable syntax in code block causing raw mode editing not to work

### ISSUE THREAD

**Issue by adioni** [typemill/typemill#285]
Hello,

One one of my pages has an instructional example bash code block with the following line in it :

`/usr/bin/mail -s "$SLURM_JOB_NAME $SLURM_JOB_ID" your_username@example.com < easy-to-remember-name-${SLURM_JOB_ID}.out`

It looks like the presence of ${SLURM_JOB_ID} is somehow messing up things when I then try to edit the page in raw mode; none of the content editor's elements appear:

[raw-mode1.png](https://postimg.cc/T58yn1dh)

Here is the console message for the page:

[raw-mode2.png](https://postimg.cc/jnXsCSCp)

If I remove the ${SLURM_JOB_ID} text back in visual mode, then raw mode editing for the page works fine once again.

**Comment by trendschau** [comment]
This is fixed in version 1.5.1 now.
