### ISSUE TITLE
external comments plug-in

### ISSUE THREAD

**Issue by michelangeli-dev** [typemill/typemill#286]
Hello

Sorry, but I don't know where to post this information !

I just integrated an external comment plug-in: HashOver.
It works perfectly with Typemill and the Cyanine theme.

If you want to know how to integrate it, I'll describe in a few days the manipulation in a new article on my blog.

Have a nice day.

**Comment by trendschau** [comment]
Great, thank you for sharing, let us know about the blog article here. I remember that there was some demand for a comment system: https://github.com/typemill/typemill/issues/186

**Comment by trendschau** [comment]
Thank you for sharing, it looks very good! You can also integrate it with a plugin if you don't want to change the theme directly, but the way you described works too. Good to know that there is a self hosted open source alternative to disqus!!

**Comment by Suitbert** [comment]
Sorry, I am not a software developer. But I would like a comment-plugin very much! Would be great, if there is someone out there, implementing it. Thanks a lot!
regards,
Suitbert

**Comment by trendschau** [comment]
thank you again for the hints for a comment system. I will close it for now since I want to focus on Bug reports right now.
