### ISSUE TITLE
Meta-content not updating

### ISSUE THREAD

**Issue by zb100** [typemill/typemill#291]
When I change the meta-content of my pages, it will not save the changes but simply revert to what was there before. For example, my Navigation Title is 'news' but I want to change it to 'News'. This is not possible for me. This is after I updated to 1.5.1.

**Comment by trendschau** [comment]
I cannot reproduce this, for me it works. Can you open the developer console of your browser and check if you see any error there? 

Please also check the permissions of your content folder and your content files, I suppose this is a permission error.

**Comment by zb100** [comment]
I get these two in the developer console:

[Error] Failed to load resource: the server responded with a status of 404 () (axios.min.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (vuedraggable.umd.min.js.map, line 0)

I have 755 permissions on all files and folders.

**Comment by trendschau** [comment]
I still cannot reproduce this behavior with none of my websites, all updated successfully. Not sure if I can help here. You can try to delete the cache in the typemill-settings (developer => green button to recreate cache), delete your browser cache and again check the permissions of the content file. You can also check if there are YAML-files for each content-file and which permissions they have.

**Comment by zb100** [comment]
Thank you for the suggestions, for some reason the problem persists. It's strange because the error only occurs on any changes in the 'meta' tab, not the 'content' tab. I can change the content absolutely fine.

**Comment by trendschau** [comment]
Very strange, and the yaml-files in the content folder are there with the correct permissions? Another idea is the htaccess, maybe yaml-files are blocked there with a custom rule somehow? Does it work on your localhost, for example?

**Comment by trendschau** [comment]
I could not reproduce this issue, please reopen the ticket if the problem still exists.
