### ISSUE TITLE
PHP 8 required after composer update

### ISSUE THREAD

**Issue by gingerbeardman** [typemill/typemill#293]
Hi,

I just installed as directed:

1. `git clone git://github.com/trendschau/typemill.git`
2. `composer update`
3. make certain folders writable

Afterwards, I got this error:

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".`

I cannot force my host to be PHP 8, so is there any way to get requirements back down to PHP 7 (as in the typemill readme). I don't know how to figure out which package has forced composer/PHP to go so high.

Thanks!

**Comment by trendschau** [comment]
Hi and thank you! 

I am not aware of PHP 8.0.2 requirement, version 1.5.1 should run with PHP 7.4 (my servers run with 7.4, too). I will test the github version again in the next days, in the meantime you could use the zipped version from the typemill website that I use for my sites.

**Comment by gingerbeardman** [comment]
Thanks! I will decide what to do when I've finished developing the site locally.

**Comment by trendschau** [comment]
I tested it today with: 

```
git clone git://github.com/trendschau/typemill.git
composer update
```

On my xampp/windows machine with php 7.4 installed and it works without problems. I also checked requirements with composer 

```
C:\xampp\htdocs\typemill>composer check-platform-reqs
Checking platform requirements for packages in the vendor dir
ext-dom        20031129    success
ext-gd         7.4.15      success
ext-json       7.4.15      success
ext-libxml     7.4.15      success
ext-mbstring   7.4.15      success
ext-simplexml  7.4.15      success
php            7.4.15      success
```

On my linux it also runs without problems. 

I am not sure why your version requires PHP8. Do you have the chance to test it on another computer/server?

**Comment by gingerbeardman** [comment]
I get this:

```
$ composer check-platform-reqs
Checking platform requirements for packages in the vendor dir
ext-dom        20031129    success  
ext-gd         8.0.13      success  
ext-json       8.0.13      success  
ext-libxml     8.0.13      success  
ext-mbstring   8.0.13      success  
ext-simplexml  8.0.13      success  
php            8.0.13      success  
```

I'm on macOS if that makes any difference.

**Comment by trendschau** [comment]
I suppose that means you are running on php 8.0.13 and that is enough for dependency-requirements. 

I checked all my live websites with 7.4 and 8 and they run without problems, live and locally. 

checked most of the dependencies manually and none require php8

So it is very likely a problem with your local setup and I can't help here. Maybe this thread can help: https://laracasts.com/discuss/channels/laravel/unable-to-run-composer-update-or-composer-install-command

So you can try to update composer and clear cache

```
composer clearcache 
composer selfupdate
```

**Comment by gingerbeardman** [comment]
OK, i think I solved it.

I am running MAMP with PHP 7.4.21 [Screenshot](https://user-images.githubusercontent.com/49612/144267529-478edcc0-754b-4092-b4e1-14cdabc705bc.png)

But my macOS system default `/usr/local/bin/php` is PHP 8.0.13 and this is what composer sees from the command line.

So I looked into it and `/usr/bin/php` is still PHP 7.3.29

Then doing `/usr/bin/php /usr/local/bin/composer update` will set everything as required for running with PHP 7.
