### ISSUE TITLE
Download buttons broken on books theme pages

### ISSUE THREAD

**Issue by gingerbeardman** [typemill/typemill#294]
Download buttons on the books main page work, but lead to broken files:
- https://books.typemill.net

Download buttons on books sub-pages, like below, lead to 404:
- https://books.typemill.net/typemill
they are as follows
- https://books.typemill.net/download?books=[object%20Object]
and display a page that says "hello"

**Comment by trendschau** [comment]
Oh, thank you, I will fix that asap!

**Comment by trendschau** [comment]
thank you again  for reporting, this is fixed now. 

The 3 ebooks are also part of the ebook-plugin, but maybe there will be more ebook layouts in future (hopefully).
