### ISSUE TITLE
Odd link to non-existent "favicon io" zip file in intro setup content

### ISSUE THREAD

**Issue by gingerbeardman** [typemill/typemill#295]
> favicon io (ZIP, 21.53 KB)

https://github.com/typemill/typemill/blob/b2b2202070517b89e1e8c517f95a119d1aba8550/content/00-welcome/00-setup-your-website.md?plain=1#L9

**Comment by trendschau** [comment]
thank you, that was testing content, I will delete it!

**Comment by trendschau** [comment]
deleted for next version

**Comment by trendschau** [comment]
version 1.5.2 is out with clean content
