### ISSUE TITLE
Can't use & character in site title

### ISSUE THREAD

**Issue by gingerbeardman** [typemill/typemill#296]
This seems unreasonable, given the character can be escaped for URL and/or encoded as entity for HTML.

> <img width="403" alt="Screen shot 2021-11-30 at 11 05 03" src="https://user-images.githubusercontent.com/49612/144036244-82207739-f472-40ff-bb22-38f7950cd50d.png">

**Comment by trendschau** [comment]
Thank you, I will fix that for the next version 1.5.2 and allow more characters there.

**Comment by trendschau** [comment]
lowered validation to nohtml for next version, so all characters allowed but no html/code

**Comment by trendschau** [comment]
version 1.5.2 is out and this should work now.
