### ISSUE TITLE
Changes in 1.5.1 (.htaccess) prevents using a Logo

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#297]
I had to revert the recent change in the .htaccess so that my SVG logo in media/files is visible.

From:
> RewriteRule ^(system|content|data|settings|(media\/files\/)) index.php [QSA,L]

To:
> RewriteRule ^(system|content|data|settings) index.php [QSA,L]

With this new htaccess, Safaris Webkit Inspector shows me: "ressource not loadable". I use `{{ base_url }}/{{ logo }}` in my theme.

**Comment by trendschau** [comment]
thank you, good point, logo should be moved to image library. I will check that for next release.

**Comment by trendschau** [comment]
fixed for next version

**Comment by trendschau** [comment]
version 1.5.2 is out now, after an update you should upload the logo again. It will be added to the image folder now, so you can use the new htaccess rules to protect the files.
