### ISSUE TITLE
ContactForm & internal Captcha 

### ISSUE THREAD

**Issue by gppixelworks** [typemill/typemill#298]
I've two different domains on a VPS.  Am exploring Typemill on both.

On one domain the ContactForm plug-in works normally with the internal captcha activated.

However on the 2nd domain ContactForm is unable to recognise a correct captcha entry.  It returns an incorrect captcha entry.

Stranger is that on the 2nd domain if the captcha textbox is left empty, the form submits and send the email.

I've compared the .vhost files for both domains and there are no differences (except, of course, the directories and such).

I ran `composer update` on the first domain during install.  I ran it also on the 2nd domain after the 1st domain was working.

It must be something simple.  Hope someone has experienced this already.

**Comment by trendschau** [comment]
Hm, that sounds strange, I tested it on my live instance and there it works as expected. Unfortunately I am not familiar with the setup  you described. Are you sure that the sessions are not shared in that setup? Maybe other users can help...

**Comment by gppixelworks** [comment]
I thought it strange too.  You were right on the sessions being shared.  That was the problem.  Thanks.

**Comment by trendschau** [comment]
happy to hear that you could solve the issue!
