### ISSUE TITLE
Not all items can be changed in Settings dialog

### ISSUE THREAD

**Issue by LiohMoeller** [typemill/typemill#30]
Some items like the Copyright and the Language cannot be changed in the Settings dialog, after initially defining them.

Changing them in the config file directly result in the correct settings, but in the Settings dialog the old values are still displayed.

**Comment by trendschau** [comment]
thank you for reporting this issue, I will check it and fix it with the next release

**Comment by trendschau** [comment]
I tested this not and for the copyright looks fine but the language is not stored. Ironically I started to write auto-tests for the configuration and missed exactly this use-case. So I will add the case to autotests and fix the issue for the next release, published in about 2 weeks....

**Comment by trendschau** [comment]
this has been fixed in version 1.2.17
