### ISSUE TITLE
how to use html / iframe in page editor?

### ISSUE THREAD

**Issue by turbopixel** [typemill/typemill#300]
I want to insert a google maps iframe into my page content. But how?

![grafik](https://user-images.githubusercontent.com/15839724/150650130-f7589c64-ac87-45ff-a4ac-8a0a759d18fb.png)

maybe a feature request: add a iframe (like youtube)

![grafik](https://user-images.githubusercontent.com/15839724/150650205-056225a2-5ed1-47e8-adda-ca319466a4b8.png)

**Comment by trendschau** [comment]
Hi Nico, the editor only accepts pure markdown, no html, and the markdown parser (parsedown) is used with safe mode (see here: https://github.com/erusev/parsedown#security). 

But you could write a small plugin to integrate maps with the new shortcode-feature. 

* Here is a documentation of the shortcode feature: https://typemill.net/plugin-developers/shortcodes
* And here is a plugin that makes use of shortcodes, so you can check the code: https://plugins.typemill.net/ebookproducts

**Comment by turbopixel** [comment]
Hi Sebastian,
I create a google maps plugin: https://github.com/turbopixel/typemill-googlemaps. It works fine!

Do you want to share the plugin in your plugin directory? (https://plugins.typemill.net/)

**Comment by trendschau** [comment]
Hi Nico, 

very cool, I tested it and it works fine, I will add it to the directory this evening or tomorrow !!!

**Comment by trendschau** [comment]
It is live now: https://plugins.typemill.net/

**Comment by jasonday** [comment]
@trendschau I do think it would be useful to have the HTML sanitization be user configurable (on/off) for those of use that are operating our own site. I realize I can achieve a two column layout with shortcodes, but it's a bit clunky

**Comment by trendschau** [comment]
I thought about it, but the htmlpurifier is nearly as large as typemill and I don't want to add a big library like that to the typemill core. I am also not super happy to switch off the safemode for the markdown parser. I will think about it again in Typemill V2. Maybe there is a way to allow html tags and to add the purifier with a plugin then.
