### ISSUE TITLE
Raw Editor converts some Entities

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#302]
When I type a non breaking space ( ) into the Raw Editor Typemill converts it into `&nbsp;`. So when editing the article again, the rendered representation also contains the string `&nbsp;`. Currently, I've to replace the string every time with the Unicode character for the non-breaking space. It also happens with the & sign, which will be convertet to `&amp;`. It only seems to happen with the Raw Editor.

**Comment by trendschau** [comment]
thank you, I will check that for the next release

**Comment by trendschau** [comment]
sorry for later reply, I was blocked, just fixed it in master. Will publish 1.5.3.2 with small changes soon.

**Comment by trendschau** [comment]
fixed with version 1.5.3.2 published today
