### ISSUE TITLE
Links Styling

### ISSUE THREAD

**Issue by HJB1972** [typemill/typemill#304]
Hi I am using the default Typemill theme and I would really like to remove the underlining from external links. Please can you tell me how this is possible - have tried various things to no avail. Many thanks.

**Comment by trendschau** [comment]
You can try with this in the custom css and after that refresh browser cache: 

````
article a, article a:link, article a:visited ,article a:hover, article a:focus, article a:active, footer a, footer a:link,footer a:visited, footer a:hover, footer a:focus, footer a:active {
  text-decoration: none;
}
````

**Comment by HJB1972** [comment]
Perfect. Thank you. It worked.
