### ISSUE TITLE
View Site in new window

### ISSUE THREAD

**Issue by HJB1972** [typemill/typemill#306]
Hi. Please can you tell me - is there a way to "View Site" in a new window from the admin area (is this something I need to set in my own browser?) or is there a way for Typemill to do this automatically? Sorry if this is something blatantly obvious - I am no tech guru! Think Typemill is awesome by the way. 
![Typemill Question](https://user-images.githubusercontent.com/100085675/155039994-361d1ba7-6daa-4abb-b081-c5cf435b49ae.png)

**Comment by trendschau** [comment]
You have to right click your mouse and then select something like "open in new window". Typemill does nearly never open links in new windows automatically because it is concidered as very bad practice: User should decide about the behavior and not the application. 

I hope this helps

**Comment by HJB1972** [comment]
It does help. Brilliant. Thank you for such a speedy response.
