### ISSUE TITLE
bug with Blockquote

### ISSUE THREAD

**Issue by cjdduarte** [typemill/typemill#309]
When I insert a Blockquote (>)
Example: > This is a test

![image](https://user-images.githubusercontent.com/42243532/155311908-d32f8ba0-6c47-4ebf-bd95-e428284fa1ad.png)

When saving, etir replaces with **"& g t ;**"

![image](https://user-images.githubusercontent.com/42243532/155312119-4cd60dbe-d2f0-49db-b63b-7f140018a9e9.png)

If you keep editing this "**& g t;**" turns to text, losing the "Blockquote" formatting

**Comment by trendschau** [comment]
ahh, thank you, probably the same issue as reported in #302 , will fix it with the next release

**Comment by trendschau** [comment]
sorry for the late reply, I was blocked with other projects. 

Now I fixed it in the master branch, it was just a stupid one-liner that caused this bug. You can use GitHub-Version or wait some days until I publish 1.5.3.2 with small changes.

**Comment by trendschau** [comment]
fixed with version 1.5.3.2 that was published today.
