### ISSUE TITLE
Navigation path problems

### ISSUE THREAD

**Issue by peter56ibb** [typemill/typemill#310]
Hello,

the Google Search Engine tells me the following navigation path problems:

- Schema "data-vocabluary.org" veraltet -

Among others on the page http://spatial-manager.bplaced.net/spatial-manager/spatial-manager-installation
Is this a problem, or can I ignore it?

Thanks in advance and kind regards,
Peter

**Comment by trendschau** [comment]
Looks like it is outdated, so it should be changed in the theme with the next release.

**Comment by trendschau** [comment]
Not sure if this is still relevant, please reopen if yes :)
