### ISSUE TITLE
message	"Slim Application Error"

### ISSUE THREAD

**Issue by lthienard** [typemill/typemill#311]
Hi,

When I want to add a file from the library the images are displayed fine but if I click on the "File" button I get this error and no files listed.

[https://ibb.co/SKThv2J](https://ibb.co/SKThv2J
)
Thank's for help

**Comment by trendschau** [comment]
Works fine in my installation. 

Can you activate the error reporting in the settings (scroll down to developer) and post the full error here? Don't forget to disable error reporting after that again. 

You can also check: 

* if you have the latest version of typemill is installed
* if the rights for the folder are set correctly
* if you have the latest version of htaccess file: https://github.com/typemill/typemill/blob/master/.htaccess
