### ISSUE TITLE
Ebook products description does not parse markdown

### ISSUE THREAD

**Issue by MysterieDev** [typemill/typemill#318]
I think in your ebookproducts plugin your forgot to parse the description markdown:

i fixed it in my installation as seen here:
`$html .= '<p>' . $this->markdownToHtml($ebookproducts[$id]['description']) . '</p>';`

before that the line was this:
`$html .= '<p>' . $ebookproducts[$id]['description'] . '</p>';`

**Comment by MysterieDev** [comment]
PR https://github.com/typemill-resources/ebookproducts/pull/1

**Comment by trendschau** [comment]
thank you very much, merged and published
