### ISSUE TITLE
Typemill - hljs plugin - add badge option and update to version 11 of hljs

### ISSUE THREAD

**Issue by MysterieDev** [typemill/typemill#319]
PR: https://github.com/typemill-resources/highlight/pull/2
![image](https://user-images.githubusercontent.com/32373099/157471229-46130835-0357-43f8-9e46-7aa4ff28dff5.png)
![image](https://user-images.githubusercontent.com/32373099/157471330-78aa99b1-453c-4302-8984-2a3da8531259.png)
![image](https://user-images.githubusercontent.com/32373099/157471381-583dbfed-8ce6-4a4b-8c99-9df062b2d4da.png)

**Comment by MysterieDev** [comment]
@trendschau for some reason I forgot to add it to the commit, but I also forgot the hljs file itself
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js

**Comment by trendschau** [comment]
thank you! Is there any reason why it uses 11.4.0 and not 11.5.0?

**Comment by MysterieDev** [comment]
Not really, I just tested it with a version I had locally, which was 11.4

**Comment by trendschau** [comment]
Hm, I still get message that  hljs.addPlugin and hljs.highlightAll not a function. Do you have a working local version and can you commit it to github?

**Comment by MysterieDev** [comment]
Yes, I'll draft a pr

**Comment by MysterieDev** [comment]
https://github.com/typemill-resources/highlight/pull/3/files try out that one, works on my installation

**Comment by trendschau** [comment]
ok, added the highlights-copy.min.css file manually and pushed it. Now it works. I will publish it later today.
