### ISSUE TITLE
Download link Website vs. Github tag?

### ISSUE THREAD

**Issue by turbopixel** [typemill/typemill#327]
What is the current version? 

Download link from the website: https://typemill.net/media/files/typemill-1.5.3.1.zip
Last github release: https://github.com/typemill/typemill/releases/tag/1.1.6 (from 2018)
Or just checkout the master branch and run `composer install`

**Comment by trendschau** [comment]
please use the website or master branch with composer install. The releases on github are old, they caused problems in the past with included libraries...

**Comment by turbopixel** [comment]
Thank you for the quick reply. I was just wondering that the version from the website is higher than in Github.sehr hoch ist.
