### ISSUE TITLE
The maximal size of a file is 20 MB

### ISSUE THREAD

**Issue by lthienard** [typemill/typemill#328]
Hello,

How to remove upload limitation?

thanks in advance

**Comment by trendschau** [comment]
Yes, good point, I have to make it configurable for next release, right now you have to hardcode it here: https://github.com/typemill/typemill/blob/master/system/Controllers/ControllerAuthorMediaApi.php#L240

Will change it with next release.

**Comment by lthienard** [comment]
Nice !

It would be nice to be able to manage the authorized file extensions also of the ControllerAuthorMediaApi.php file

Thank you

**Comment by trendschau** [comment]
yes, good point, I will see what I can implement for next release...

**Comment by lthienard** [comment]
For more 20mb update too 2 JS File **vue-shared.js** and **vue-blox.js** on **system\author\js**

**Comment by trendschau** [comment]
Ok, this is implemented in Version 1.5.3.3 now, you can add any size in the system settings. Be aware that server might have some limitations for large file uploads. I did not test every detail but for editor and plugins (metatab uploads) it worked without problems.
