### ISSUE TITLE
Markdown Admonitions

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#33]
A question to the community: What do you think about markdown admonitions (notices like warning), that care pretty widespread in documentations. The problem is that they are not standard in markdown. 

Syntax for restructrued text

```
.. notetype:: Text
```

Syntax supported by Pandoc

```
:::title
Admonition Text
:::
```

Syntax of python markdown (e.g. MKdocs):

```
!!! Note "Headline"
    This is the note message
```

Syntax of Grav CMS and Lektor CMS:

```
! Admonition with 
! green design

!! Admonition with
!! yellow design

!!! Admonition with
!!! red design
```

Everything has its ups and downs, the syntax of Grav feels semantically fine, but is unsupported elsewhere. Any other suggestions? Or should Typemill not support admonitions at all?

**Comment by Tekl** [comment]
From the perspective of a plain text file reader I would prefer the MKdocs way.

Maybe you could also think about a more general way like this: https://dimerapp.com/syntax-guide/alerts

```
[warn]
Warning
[/warn]
```
This could be transformed to:
```
<aside class="warn">
Warning
</aside>

That would also be usefull to wrap a section like a download box with file size and additional links into a styleable container.

**Comment by trendschau** [comment]
I decided for the "!" syntax of Grav and other Flat-File-CMS in version 1.3.6. because it is then at least compatible to them and the syntax is closest to the markdown philosophy in my eyes.
