### ISSUE TITLE
Support docker deployment

### ISSUE THREAD

**Issue by matbgn** [typemill/typemill#337]
Hi,

I didn't see any mention of Docker in the issues (except on the discussion of Typemill v2) so forgive me if I missed some. 

Would you accept a PR for a simple integration of Docker in the project to give the ability for people who don't want to install PHP locally to have a quick workaround? 

The end commit should not have more than three files/folder added to the master root path: a Dockerfile, a .dockerignore & a docker-utilities folder with some bash boot scripts for Docker.

Also I would provide a how-to documentation for the installation path in the place and form of your choice.

What do you think before I start coding this? What would be the macro steps to take care of you would advice?

Thanks in advance a have a great day!

**Comment by trendschau** [comment]
Hi Matthieu, 

that is highly welcome, thank you!!

Have a great day
Sebastian

**Comment by matbgn** [comment]
Solved by #338

**Comment by trendschau** [comment]
Sooooo, this is published with 1.5.3.3 now, great contribution!!!
