### ISSUE TITLE
Add fields besides title and content

### ISSUE THREAD

**Issue by kerngebiet-digital** [typemill/typemill#34]
Tipemill is great so far! 
It is missing additional fields besides title and content. This is very critical especially for SEO. Currently it takes the description and title globally. The system for the theme and plugin fields could also work for content creation. This CMS is great for handbooks and documentations but would be even better for heavy Text sites and SEO Pages.
Chris

**Comment by trendschau** [comment]
Hi Chris, 

thank you for your feedback and you are right: Additional fields for meta-informations and other content is missing right now, but they will follow soon: 

* With next release 1.2.19 I will finish the 1.2.X-series for the visual editor
* Then I will start with 1.3.X series that will implement exactly that: Meta-informations for pages. 

The plan is to store it in additional YAML fields and to make it extensible for plugins (and themes maybe). I hope I can start in december with it, but it will probably take some time/steps to finish. 

This is also related to issue #24

**Comment by kerngebiet-digital** [comment]
Hi Sebastian,
thank you for your Feedback. I just checked multiple flat file cms and there is no comparisment to the text editing feature together with the textarea and category drag drop feature. Absolutely gorgeous for a large SEO oriented website!

Grüße nach Berlin
Chris

**Comment by trendschau** [comment]
Hi Chris, that is nice to hear, thank you! And yes, I run my own website "cmsstash" with typemill and can confirm that search engines love that kind of simple structured websites with lots of relevant text :)

**Comment by trendschau** [comment]
With version 1.3.0 Typemill has a [meta-tab](https://twitter.com/typemill/status/1212674460995801088) with the fields 

* meta-title 
* meta-description 
* author

More fields will follow with the next versions, you can also add your own fields or even create new tabs with a plugin, but it is experimental right now and not documented yet.

**Comment by trendschau** [comment]
Version 1.3.1 implements (nearly) all fieldtypes now and allows individual meta-tabs with plugins. Read the full documentation for forms here: https://typemill.net/forms
