### ISSUE TITLE
can't login after upgrade to 1.5.3.2

### ISSUE THREAD

**Issue by Kuuke** [typemill/typemill#341]
I'm new to TypeMill. So I'm taking my first steps with this CMS. Probably I did something wrong by myself but I don't see what...

After installing 1.5.3.1 and making a first website there was an upgrade from 1.5.3.1 to 1.5.3.2.
First: Cyanine theme from 1.5.3.1 to 1.5.3.2 succesfull
Second: upgrade Typemill from 1.5.3.1 to 1.5.3.2 (using zip-file from website): website seems functional but can't login --> blank screen
seems to be that al pages behind /tm/ produce a blank screen

Upgrade method:
1. deleted system folder and replaced with system-folder from Typemill 1.5.3.2 --> can't login, blank pages, site seems functional
2. after backup: deleted folders cache, plugins, system, themes and upload new folders: can't login, blank pages, site seems functional

System: Apache/PHP 8.1
Plugins: mail 1.1.0, contactform 1.1.2 and googlemaps 1.1.0
Themes: cyanine active, newFolderTypemill (inactive)

After enabling error messages in settings.yaml this error appears when trying to login:

Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: A colon cannot be used in an unquoted mapping value at line 264 (near "THE_FOLLOWING_OPTIONS_ARE_ONLY_FOR_DEVELOPERS: De volgende opties zijn alleen voor ontwikkelaars en ervaren beheerders. Wijzig de opties alleen als u ze echt begrijpt. Bijvoorbeeld: Activeer nooit de foutrapportage voor een live website, gebruik deze optie alleen voor het oplossen van fouten."). in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/symfony/yaml/Parser.php:811 Stack trace: #0 /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/symfony/yaml/Parser.php(354): Symfony\Component\Yaml\Parser->parseValue() #1 /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/symfony/yaml/Parser.php(97): Symfony\Component\Yaml\Parser->doParse() #2 /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/symfony/yaml/Yaml.php(80): Symfony\Component\Yaml\Parser->parse() #3 /var/www/vhosts/xxxxx.nl/httpdocs/system/Models/WriteYaml.php(18): Symfony\Component\Yaml\Yaml::parse() #4 /var/www/vhosts/xxxxx.nl/httpdocs/system/Translations.php(44): Typemill\Models\WriteYaml->getYaml() #5 /var/www/vhosts/xxxxx.nl/httpdocs/system/system.php(274): Typemill\Translations::loadTranslations() #6 /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/pimple/pimple/src/Pimple/Container.php(122): {closure}() #7 /var/www/vhosts/xxxxx.nl/httpdocs/system/system.php(302): Pimple\Container->offsetGet() #8 /var/www/vhosts/xxxxx.nl/httpdocs/index.php(5): require('...') #9 {main} thrown in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/symfony/yaml/Parser.php on line 811

There are more errors visible but these errors are already visible in 1.5.3.1 and don't change in 1.5.3.2 They are mainly related to "SLIM" and probably php 8.1 and not related (I think) to my login problem after upgrading to 1.5.3.2:

Deprecated: Return type of Slim\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 112

Deprecated: Return type of Slim\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 124

Deprecated: Return type of Slim\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 135

Deprecated: Return type of Slim\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 145

Deprecated: Return type of Slim\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 155

Deprecated: Return type of Slim\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Collection.php on line 165

Deprecated: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/slim/Slim/Http/Uri.php on line 717

Deprecated: Return type of Slim\Views\Twig::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/twig-view/src/Twig.php on line 197

Deprecated: Return type of Slim\Views\Twig::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/twig-view/src/Twig.php on line 209

Deprecated: Return type of Slim\Views\Twig::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/twig-view/src/Twig.php on line 220

Deprecated: Return type of Slim\Views\Twig::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/xxxxx.nl/httpdocs/system/vendor/slim/twig-view/src/Twig.php on line 230

Domain name replaced by xxxxx ;)

**Comment by trendschau** [comment]
There are errors in some language files (colons in the yaml files), I have to fix it next week end then you can upgrade to 1.5.3.3

Sorry for that!

**Comment by Kuuke** [comment]
Take your time. Already happy there is a solution ;)

**Comment by Kuuke** [comment]
I recognize where the error is. Fixed it in de nl.yaml file. Blank pages are gone and I can login. System now reports 1.5.3.2.

**Comment by trendschau** [comment]
Great, I fixed all files in version 1.5.3.3 that has been published yesterday.
