### ISSUE TITLE
Blog post list: slug is used for headline instead of post title?

### ISSUE THREAD

**Issue by thorsten-panknin** [typemill/typemill#344]
Hey,

running Typemill 1.5.3.3 on Uberspace, aboutme theme.

On the blog page, „/blog“ in the list of blog entries, the slug of a post is shown as the headline, please see screenshot

![grafik](https://user-images.githubusercontent.com/1814897/179306137-15e616d8-d468-41c5-9d9b-d8b7d0326d23.png)

I'd assume that the title of the post would be used („Zwischenstand vom 23.06.2022“), but apparently that's not the case, it's the posts's slug. Is there a reason for this or could this be a bug? I'm not a programmer, so please forgive me if the solution is obvious. Still learning.

**Comment by trendschau** [comment]
According to the theme-code it is the page meta title, not the slug: https://github.com/typemill-resources/aboutme/blob/master/folder.twig#L49

You can edit the page meta title in the meta tab. If it does not work, please try to hard refresh the page or to delete the cache with the button in the system settings. 

If it does not work either, let me know and I try to check next week

**Comment by thorsten-panknin** [comment]
Thanks for getting back to me. I'd already hard-refreshed the page and additionally edited the page meta title, see screenshot.

![grafik](https://user-images.githubusercontent.com/1814897/179350090-f7c330db-93e7-432f-b6ed-49c9b062d761.png)

Recreated the cache now as you advised, doesn't work for me, sadly.

I looked through the theme variable docs to maybe spot an error or something, but couldn't find post.meta-title there.

The situation isn't time-critical since I'm only preparing a switch from another CMS to Typemill in my sparetime. I'd be happy for you to take a look. :)

**Comment by thorsten-panknin** [comment]
I'm not sure what caused the problem, but I could solve the situation by recreating the blog post. When I tried to add it on the blog page in the backend, the system moaned about the two „.“ in the date which I temporarily removed and re-added in the title and meta title a bit later.
