### ISSUE TITLE
Documentation: Links to Twig website in theming docs are outdated

### ISSUE THREAD

**Issue by thopanX** [typemill/typemill#347]
Hey,

I was perusing the theming documentation and found that the links to the Twig site are outdated, because the project has moved to the Symphony project. The Typemill documentation page in question is: https://typemill.net/theme-developers/twig

## Working links
Templates: https://twig.symfony.com/doc/2.x/templates.html
Filters: https://twig.symfony.com/doc/2.x/filters/index.html
Functions https://twig.symfony.com/doc/2.x/functions/index.html
Documentation; https://twig.symfony.com/doc/2.x/

**Comment by trendschau** [comment]
Thank you, I will update it asap

**Comment by thorsten-panknin** [comment]
If you want help with such stuff and can give me secure access to the docs, I volunteer.

**Comment by trendschau** [comment]
very sad, but asap was nearly two years in this case. I am updating the documentation to version 2 now, the past two years did not left time for anything unfortunately...
