### ISSUE TITLE
DEV-Theme does not render, displays a Slim Application Error

### ISSUE THREAD

**Issue by thopanX** [typemill/typemill#357]
Using Typemill 1.5.3 and DEV theme 1.2.0 with PHP 8.1.9's in-built development webserver on Linux. Webserver output:

`[Fri Sep  2 19:59:13 2022] [::1]:44172 [500]: GET /`

Standard cyanine theme works though.

**Comment by trendschau** [comment]
typemill does not work with php 8.1, only php 8.0. I wonder that the cyanine theme works with that setup. Error message only says that it is a 500 server error I suppose...

**Comment by thorsten-panknin** [comment]
Yeah, nothing else, alas. I'll see that I downgrade to 8.0 then. Thanks!

**Comment by thorsten-panknin** [comment]
I downgraded to PHP 8.0.23, still getting that 500, sadly. No other output. Any idea? Is the .0.23 a problem?

**Comment by thorsten-panknin** [comment]
I've sent you the Slim application error output in a separate mail.

**Comment by trendschau** [comment]
It works well in my test-installation. The message you send me says that it does not find the index.twig in the theme folder. Make sure that the theme is installed correctly and files are readable.
