### ISSUE TITLE
Reading time?

### ISSUE THREAD

**Issue by thorsten-panknin** [typemill/typemill#359]
Can somebody give me a hint on how to get the number of characters in the content variable–so I can calculate an approximate reading time? I found twig's length filter, but when I try to output it via `{{content|length}}` the webserver returns an error 500.

**Comment by trendschau** [comment]
the content variable outputs html and the length filter does not accept it. You should create a plugin that counts the length of the pure markdown content and then output it in the template.

**Comment by thorsten-panknin** [comment]
Alright, thanks.

12.09.2022 09:54:15 trendschau ***@***.***>:

**Comment by trendschau** [comment]
or maybe even better: try a frontend solution with JS, I am sure that there are tons of libraries for that :D

**Comment by thorsten-panknin** [comment]
I've decided to learn how to code plugins for Typemill, and am working through the documentation/tutorial. Found a 404:

https://typemill.net/plugin-developers/tutorial/write-the-php-file > You can find a list of all events in the `Event Overview in the documentation](https://typemill.net/for-plugin-developers/documentation/event-overview)`. > The correct URL is https://typemill.net/plugin-developers/event-overview

**Comment by trendschau** [comment]
I have to correct myself: content|length in templates work totally fine for me and it is also possible to strip tags with content|striptags|length

I will close this because there is no issue.

**Comment by trendschau** [comment]
thank you for sharing!
