### ISSUE TITLE
Mail plugin form should have autocomplete set as off

### ISSUE THREAD

**Issue by jasonday** [typemill/typemill#366]
![image](https://user-images.githubusercontent.com/748011/195131910-33a643eb-6c39-4842-8311-c11ce26e64e2.png)

Because chrome (or other password  managers) save credentials, those credentials get automatically filled into the username and password fields of the SMTP section of the Mail plugin. So, anytime I go in to any plugin settings, I have to remember to clear these fields, otherwise I receive an error. 

Adding `autocomplete="off"` to the form or to the individual fields would prevent this issue. 

`<form method="post" action="/form" autocomplete="off">
  …
</form>

**Comment by trendschau** [comment]
Thank you, works great, I merged and published a new version.
