### ISSUE TITLE
save button not reachable

### ISSUE THREAD

**Issue by bartart3d** [typemill/typemill#370]
Hello, 
this is a layout issue I couldn't work around.
With longer pieces of text (I copy pasted it as text into a new article) I could not reach the 'save/cancel' buttons at the bottom of the entry field because of the bar at the bottom of the page saying 'publish - discard' etc... I guess it's above the button, making it impossible to click. scrolling lower didn't help.
I'm a new user, I guess there must be solution, I'll probably won't be the only one.

thanks,
Bart

**Comment by trendschau** [comment]
I will try to reproduce that behavior.

**Comment by trendschau** [comment]
Yes, this is fixed in version 2. There is an autoscroll on every new line so the focus while writing should stay where it is on the screen now.
