### ISSUE TITLE
Show number of times an article has been viewed

### ISSUE THREAD

**Issue by thopanX** [typemill/typemill#374]
I don't need a full-fledged analytics suite, but having an idea about how popular an article is, would be practical for me. HTMLy has this (from where I came to Typemill). 

Maybe this is something for Typemill 2

**Comment by trendschau** [comment]
Thank you, it is a good idea but my problem is the very limited time and the very long list of work, so I think I cannot implement this in near future. It should be possible with a plugin, but most people will probably use an external analytics-tool with the existing analytics plugin. Anyway, I will add it to the backlog and see if there is demand for that feature.
