### ISSUE TITLE
Possibility to embed Sketchfab via HTML

### ISSUE THREAD

**Issue by crixus96** [typemill/typemill#387]
Hello all,

Thank you very much for the great CMS Typemill. I have tried a few different CMS. I got stuck with Typemill and am currently building my site with it. 

Currently I have the requirement to integrate a 3D model from Sketchfab via HTML. I have not yet been successful with HTMLopen and HTMLclose. 
https://github.com/typemill/typemill/issues/367

Furthermore, I have read that the integration of HTML is not desired.
https://github.com/typemill/typemill/issues/109

Is there currently a "workaround" to integrate HTML nevertheless?

I think the CMS is great for my purposes and would like to continue using it.

Thank you for your help and best regards

**Comment by trendschau** [comment]
Hi Crixus, 

such integrations should be easily possible with a small plugin and a shortcode. It requires some small coding-skills. https://typemill.net/plugin-developers/shortcodes

Integration of html is only possible with the htmlOpen/htmlClose button. I think about native integration in Typemill 2 with something like htmlopen/htmlclose, but that is lower prio and V2 takes some time.

**Comment by crixus96** [comment]
Hi Trendshow,

I have done it myself! It was really easier than I thought: 
https://github.com/crixus96/typemill-sketchfab/tree/main/sketchfab

I have no idea about PHP, but I was able to follow HTMLopen ;). 

Thanks for your commitment to Typemill and good luck for the 2 version!

Many greetings
