### ISSUE TITLE
Strings without localization functions

### ISSUE THREAD

**Issue by hide-me** [typemill/typemill#391]
I don't know how to add it, so thats why was created this issue
![example_2_tm_content_visual](https://user-images.githubusercontent.com/45032974/215274754-598c4ffb-48fc-4d04-83d9-cc8c82d55006.png)

**Comment by trendschau** [comment]
yes, that is probably in the vue templates here: https://github.com/typemill/typemill/blob/master/system/author/js/vue-meta.js#L28

I will fix that for Typemill Version 2 but I won't update Version 1 anymore because of a super lack of time ...

**Comment by trendschau** [comment]
Added most strings in Typemill v2 and will improve it further in future versions.
