### ISSUE TITLE
I cant't remeber my password

### ISSUE THREAD

**Issue by yesilovebooks** [typemill/typemill#402]
Hi!

Unortunately, I really can't remeber my password anymore...
How can I recorver it, please?

Thank you.

**Comment by yesilovebooks** [comment]
Hi again!

I found out the answer to my question in this link:

[https://typemill.net/writers/forgot-password](https://typemill.net/writers/forgot-password)

Eveythin is fine now.

**Comment by trendschau** [comment]
glad to hear that!
