### ISSUE TITLE
get a "500 Internal Server Error" after Update to 1.2.18 

### ISSUE THREAD

**Issue by glimpse-of-life** [typemill/typemill#48]
Hi, get a "500 Internal Server Error" and blank page after Update to 1.2.18 following the rules  on https://typemill.net/getting-started/update

My page: https://hotdocs.carsten-nichte.de

All Folders are 775 or 774...

??? No idea how to get rid of this. Any Idea?

vg Carsten

**Comment by trendschau** [comment]
You can activate the error reporting. Open the settings.yaml file in settings folder (or create it if it does not exist) and add this line: 

`displayErrorDetails: true`

Then go to the page and post the error message here.

You could also check the error logs on your server.

**Comment by glimpse-of-life** [comment]
Hi, "displayErrorDetails: true" displays nothing - all I got is a blank page an the "500 Internal Server Error", unfortunately I have no access to the server logs at my provider, and php logging is disabled either.

I created an info.php in the root folder, and the phpinfo showed up... don't know if this is a good sign.

Tomorrow I will set up typemill on my local apache, to test the stuff, perhaps that gives me a hint what's going wrong...

**Comment by glimpse-of-life** [comment]
on my local server I got an error: 

`Warning:` require_once(/Users/cnichte/Apache2-www/typemill web/system/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in /Users/cnichte/Apache2-www/typemill-web/system/vendor/autoload.php on line 5

he missed the composer folder.  So I followed the manual-path:

`git clone "https://github.com/trendschau/typemill.git"
`composer` update

All folders appear. Copied my content, media an setting folders.... and all worked fine on my local server.

I copied the whole stuff to my domain, and all I get is a blank site :-/

My Webseite: https://hotdocs.carsten-nichte.de

even with https://hotdocs.carsten-nichte.de/setup/ or with https://hotdocs.carsten-nichte.de/index.php

The virtual host is connected to the webspace, so info.php shows up:
https://docs.carsten-nichte.de/info.php

I am a  little clueless at the moment - localhost works - webspace don't work... any ideas?

**Comment by trendschau** [comment]
If it works locally, then the reason is your live environment. 

Please follow the documentation on typemill.net (system requirements and installation hints), make sure that you meet the system requirements and that you set the correct rights to the folders and files as described there. 

From the first view, I cannot find any module in your phpinfo on your live server, looks like you do not have mod_rewrite enabled, you also have to allow htaccess on your server.

In case of trouble you should contact your hoster and ask him how to enable it.

I hope this helps...

**Comment by trendschau** [comment]
Could you solve your problems and can we close this issue?

**Comment by glimpse-of-life** [comment]
No, its not solved. Ive no idea what's the cause for this. Now i use Wordpress with MinervaKB-Plugin and WP Githuber MD for Markdown. Its not the best solution, but it works for now, so that I can get on with my project. I will keep an eye on Typemill and try it again later. I think we close this issue for now.
