### ISSUE TITLE
Anchor points in Typemill ?

### ISSUE THREAD

**Issue by carstenwm** [typemill/typemill#54]
Can I use anchor points In markdown without html? (Raw Mode)

**Comment by trendschau** [comment]
It should add attributes like ID and Classes to headlines, so you could link to them, but for some reasons it does not, I probably forgot to implement. I will try to add it to the next release

**Comment by trendschau** [comment]
Hi Carsten, 

Typemill has some hidden features and even I forget about them sometimes :D 

Typemill automatically adds IDs to all headlines, so you can simply link to those headlines. You can see the ID in the html document in frontend, a headline like "My nice headline" gets the id="my-nice-headline", so you can link to the headline with "#my-nice-headline". 

I will improve this in the next release, e.g. show the id for headlines with a link-icon in the visual editor. 

Hope this helps!
Sebastian

**Comment by carstenwm** [comment]
Oh ! Well, as an 'oldie' I should have thought of this. Thank you for pointing it out.

I can make the absolute links work, not the relative urls, but I've lots of holes in my knowledge 

Inline anchors can't be done when html can't be used , right?

**Comment by trendschau** [comment]
Hi Carsten, 

there is a new feature in the system settings called "show anchor points". If activated typemill adds a linked "#" next to each headline if a user hovers over the headline. So anchor points to headlines are better visible now. It is properly styled only in the new version of typemill standard theme for now...
