### ISSUE TITLE
Setup Logo

### ISSUE THREAD

**Issue by JSG01** [typemill/typemill#58]
Hey there,

i have the following question.

Is there a way to change the Text-Title to an image?

Thanks for your help

**Comment by trendschau** [comment]
Right now you can only hardcode the image into the theme. I have to add an image upload to the form-builder for it or a fixed image upload into the system settings.

**Comment by trendschau** [comment]
Maybe I will add that to the next release because Typemill needs an upload-field for images and files anyway and I also plan to improve the image management. It might take a while ...

**Comment by trendschau** [comment]
This is deployed with version 1.3.4 now. You can upload your logo and your own favicon. This is only supported by the standard theme right now, other themes will follow...
