### ISSUE TITLE
Create video tutorials

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#69]
Video tutorials are a great onboarding for new users and developers. They can be integrated into the documentation as an easy starting-point for each chapter: 

- [ ] Typemill setup (typemill setup, settings, plugins, themes)
- [ ] Short demonstration for authors (editors, page creation)
- [ ] Tutorial theme development
- [ ] Tutorial plugin development

My english is not good enough, so one idea is to hire a professional (e.g. codecourse) and finance it with a campaign (kickstarter or something similar).

**Comment by MitteMedia** [comment]
Im going to try this but it can take a bit.

**Comment by trendschau** [comment]
Thank you all again, some videos are online: https://www.youtube.com/channel/UCyghKiX2kK9QIqTf1WT1Xxw
