### ISSUE TITLE
paragraph block non editable in visual mode

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#82]
Hey Sebastian,
When a header had been typed in raw mode followed by a paragraph of text and they are not separated by an empty line (only a line break), it's OK in markdown. They are correctly rendered in html.
But if you switch to Visual mode, it 's impossible to edit the paragraph to make a change. Both header and paragraph end up on the same block. Simply adding and empty line between them in raw mode is enough to solve this but that seems to be a bug...

Olivier

**Comment by trendschau** [comment]
Hi Olivier, 

yes, the visual markdown editor has not a super clean markdown logic, will add a fix-label, but to clean it up completely I have to analyse the whole markdown document in depth and I want to avoid it right now...

**Comment by trendschau** [comment]
#55 with more bugs with markdown parsing.

**Comment by trendschau** [comment]
starting with version 1.4.0 the markdown-blocks for the visual editor are detected with the parsedown-library, this should solve all issues with markdown in visual mode.

**Comment by trendschau** [comment]
published with version 1.4.0
