### ISSUE TITLE
Set multiple images in a row

### ISSUE THREAD

**Issue by zensudo** [typemill/typemill#83]
Hey there,

i was trying to set two images side by side. Once in class "left" and the other in class "right" but this seem not to work. How can i add two or more images in one row?

**Comment by trendschau** [comment]
I never tried it and there is probably no clean way to do it right now. However I checked it on my live page and you can add two images with class "left" and then add something like this in your custom theme-css: 

```
article img.left {
    width: 50%;
    max-width: 100%;
    float: left;
    margin: 10px 0;
}
```

This produced the following in frontend: 

![float-left](https://user-images.githubusercontent.com/2714547/75421388-6ecb1680-593a-11ea-858f-74bf2d42da92.png)

Once again, this is not very clean but maybe enough for your needs right now. For a clean solution you have to use a html-div-element. But HTML is disabled in markdown from Typemill for security reasons, so this should be done by a new content-component or something similar...

**Comment by svanlaere** [comment]
Can it be made a setting where one can enable/disable HTML usage in Markdown?

**Comment by trendschau** [comment]
Using html in markdown is pretty unsecure and I have to do a lot of security stuff for that. I will look into that but I don`t think that I will add such a feature in near future ...

**Comment by trendschau** [comment]
Here are some more tips for styling images in markdown: https://www.xaprb.com/blog/how-to-style-images-with-markdown/

The recommended way is to add a hash-tag to the image-url like this:

```
![Kitten](/media/2018/08/kitten.jpg#thumbnail)
```

and then style it in css like this:

```
img[src*="#thumbnail"] {
   your style
}
```

With the next release 1.3.4 I want to improve the media-management, so I will test and try to create a component for several images in one row....

**Comment by trendschau** [comment]
Not on the roadmap right now, but it might get relevant in the future again.
