### ISSUE TITLE
.gitignore file needs update

### ISSUE THREAD

**Issue by oliviercrouzet** [typemill/typemill#87]
Hey Sebastian
Seems that your _00-welcome_  directory has not any more a first uppercase letter so git is not any more ignoring it :
content/00-Welcome/index.yaml
Also, I believe you could just put it this in one line if you have not another _content_ directory  elsewhere :
content/

Olivier

**Comment by trendschau** [comment]
Thank you, I forgot that and will check it. Usually it should add only the .md files and exclude the yaml files. The filenames have been changed in last release to separate them from navigation names. They use the slug now and there is no uppercase anymore. 

I will update it  the next release...

**Comment by trendschau** [comment]
fixed with version 1.3.5
