### ISSUE TITLE
New emergency theme

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#98]
Created a quick fork of the emergency site by Max Böck. The [forked emergency theme](https://themes.typemill.net/emergency) is published on the theme page as a complete typemill distribution that contains:

* Typemill CMS
* Emergency Theme
* Demo Content

So you can download, upload, edit and run that website without any hazzle. It is especially designed for Organisations that want to provide information with low bandwidth and have no technical background to setup a static website like described in the original concept by Max Böck.

**Comment by Tekl** [comment]
Thanks for the great theme. It seems that it does not support widgets like search, is that intended?

Also the JS console throws an error that it can't find `sw.js`.
